const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const KEY='jjongfocus_v0_1_state'; let state=loadState(),timerInterval=null,brainInterval=null,pendingImages=[],clarifyId=null;
function defaultState(){return{items:[],nowId:null,focusMinutes:10,timerRemaining:600,timerRunning:false,timerEndsAt:null,sort:'desc'}}
function normalizeItem(x){return Object.assign({kind:'unclassified',when:'',priority:0,nextAction:'',completedAt:null},x)}
function loadState(){try{const s=Object.assign(defaultState(),JSON.parse(localStorage.getItem(KEY)||'{}'));s.items=(s.items||[]).map(normalizeItem);return s}catch{return defaultState()}}
function saveState(){localStorage.setItem(KEY,JSON.stringify(state))} function uid(){return crypto.randomUUID?crypto.randomUUID():Date.now().toString(36)+Math.random().toString(36).slice(2)}
function esc(s=''){return String(s).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]))} function nowIso(){return new Date().toISOString()}
function fmtDate(i){return new Intl.DateTimeFormat('ko-KR',{month:'numeric',day:'numeric',hour:'2-digit',minute:'2-digit'}).format(new Date(i))} function isToday(i){if(!i)return false;const a=new Date(i),b=new Date;return a.toDateString()===b.toDateString()}
function toast(m){const t=$('#toast');t.textContent=m;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),1800)}
function autoTitle(b,t){const c=(b||'').trim().split(/\n+/)[0].slice(0,44);return c||(t==='image'?'스크린샷':'새 메모')}
function addItem({type='note',title,body='',image=null}){const x=normalizeItem({id:uid(),type,title:title||autoTitle(body,type),body,image,status:'inbox',createdAt:nowIso()});state.items.unshift(x);saveState();render();return x}
const kindMeta={unclassified:['미정',''],task:['할 일','🔥'],idea:['아이디어','💡'],reference:['참고','📚'],someday:['나중에','⏳']};
function badges(x){let a=[];if(x.kind&&x.kind!=='unclassified')a.push(`<span class="badge">${kindMeta[x.kind][1]} ${kindMeta[x.kind][0]}</span>`);if(x.when==='today')a.push('<span class="badge today-badge">⭐ 오늘</span>');if(x.nextAction)a.push(`<span class="badge action-badge">👣 ${esc(x.nextAction)}</span>`);return a.join('')}
function visual(x){return x.image?`<img class="thumb" src="${x.image}" alt="스크린샷">`:`<div class="item-icon">${x.type==='brain'?'🧠':'✏️'}</div>`}
function card(x,mode='inbox'){const acts=mode==='done'?`<button class="mini-btn" data-act="restore">복원</button>`:mode==='today'?`<button class="mini-btn now-mini" data-act="now">🔥 NOW</button><button class="mini-btn" data-act="clarify">정리</button>`:`<button class="mini-btn" data-act="clarify">정리</button><button class="mini-btn now-mini" data-act="now">🔥 NOW</button><button class="mini-btn" data-act="delete">삭제</button>`;return `<article class="item-card" data-id="${x.id}">${visual(x)}<div><div class="item-title">${esc(x.title)}</div><div class="item-meta">${fmtDate(x.createdAt)}${mode==='done'&&x.completedAt?' · 완료 '+fmtDate(x.completedAt):''}</div><div class="badges">${badges(x)}</div>${x.body?`<div class="item-body">${esc(x.body)}</div>`:''}</div><div class="item-actions">${acts}</div></article>`}
function bindActions(root){$$(`${root} [data-act]`).forEach(b=>b.onclick=()=>handleAction(b.closest('[data-id]').dataset.id,b.dataset.act))}
function render(){renderInbox();renderToday();renderNow();renderDone();renderPresets()}
function renderInbox(){let a=state.items.filter(x=>x.status==='inbox');a.sort((x,y)=>state.sort==='desc'?y.createdAt.localeCompare(x.createdAt):x.createdAt.localeCompare(y.createdAt));$('#inboxList').innerHTML=a.map(x=>card(x)).join('');$('#inboxCount').textContent=`${a.length}개 · 미정 ${a.filter(x=>x.kind==='unclassified').length}개`;$('#inboxEmpty').classList.toggle('hidden',a.length>0);bindActions('#inboxList')}
function renderToday(){let a=state.items.filter(x=>x.status==='inbox'&&x.when==='today');a.sort(scoreSort);const top=a[0];$('#todayHero').innerHTML=top?`<div class="today-hero"><div><div class="hero-kicker">TODAY'S ONE</div><h2>${esc(top.title)}</h2><p>${top.nextAction?'첫 행동 · '+esc(top.nextAction):'첫 행동을 정하면 시작이 쉬워져요.'}</p></div><button class="primary-btn" data-today-now="${top.id}">🔥 이거 시작</button></div>`:'';$('#todayList').innerHTML=a.slice(1).map(x=>card(x,'today')).join('');$('#todayEmpty').classList.toggle('hidden',a.length>0);bindActions('#todayList');$$('[data-today-now]').forEach(b=>b.onclick=()=>handleAction(b.dataset.todayNow,'now'))}
function score(x){let s=0;if(x.when==='today')s+=50;if(x.kind==='task')s+=20;if(x.nextAction)s+=12;const age=(Date.now()-new Date(x.createdAt))/864e5;s+=Math.min(15,age);return s} function scoreSort(a,b){return score(b)-score(a)||b.createdAt.localeCompare(a.createdAt)}
function handleAction(i,a){const x=state.items.find(z=>z.id===i);if(!x)return;if(a==='now'){if(state.nowId&&state.nowId!==i){const p=state.items.find(z=>z.id===state.nowId);if(p)p.status='inbox'}state.nowId=i;x.status='now';x.kind=x.kind==='unclassified'?'task':x.kind;state.timerRemaining=state.focusMinutes*60;state.timerRunning=false;state.timerEndsAt=null;saveState();render();switchView('now');toast('NOW에는 이 일 하나만 둡니다.')}if(a==='clarify')openClarify(i);if(a==='delete'){state.items=state.items.filter(z=>z.id!==i);saveState();render()}if(a==='restore'){x.status='inbox';x.completedAt=null;saveState();render()}}
function openClarify(i){clarifyId=i;const x=state.items.find(z=>z.id===i);$('#clarifyPreview').innerHTML=`<strong>${esc(x.title)}</strong>${x.image?`<img src="${x.image}">`:''}`;$('#clarifyNextAction').value=x.nextAction||'';$('#taskFields').classList.toggle('hidden',x.kind!=='task');$$('#kindChoices button').forEach(b=>b.classList.toggle('selected',b.dataset.kind===x.kind));$$('#whenChoices button').forEach(b=>b.classList.toggle('selected',b.dataset.when===x.when));$('#clarifyDialog').showModal()}
$$('#kindChoices button').forEach(b=>b.onclick=()=>{const x=state.items.find(z=>z.id===clarifyId);x.kind=b.dataset.kind;$('#taskFields').classList.toggle('hidden',x.kind!=='task');$$('#kindChoices button').forEach(q=>q.classList.toggle('selected',q===b))});$$('#whenChoices button').forEach(b=>b.onclick=()=>{$$('#whenChoices button').forEach(q=>q.classList.toggle('selected',q===b));state.items.find(z=>z.id===clarifyId).when=b.dataset.when});
$('#saveClarifyBtn').onclick=()=>{const x=state.items.find(z=>z.id===clarifyId);if(!x)return;if(x.kind==='unclassified')x.kind='task';if(x.kind==='task'){x.nextAction=$('#clarifyNextAction').value.trim();if(!x.when)x.when='week'}saveState();$('#clarifyDialog').close();render();toast(x.when==='today'?'오늘로 정리했어요.':'정리했어요.')};$('#deleteClarifyBtn').onclick=()=>{state.items=state.items.filter(z=>z.id!==clarifyId);saveState();$('#clarifyDialog').close();render();toast('버렸어요.')};
function renderNow(){const x=state.items.find(z=>z.id===state.nowId&&z.status==='now');$('#nowEmpty').classList.toggle('hidden',!!x);$('#nowPanel').classList.toggle('hidden',!x);if(!x){stopTimer();return}$('#nowPreview').innerHTML=`<div class="now-card">${x.image?`<img src="${x.image}">`:''}<h2>${esc(x.title)}</h2>${x.body?`<p>${esc(x.body)}</p>`:''}</div>`;$('#nextActionInput').value=x.nextAction||'';resumeTimerIfNeeded();updateTimerDisplay()}
function renderDone(){const a=state.items.filter(x=>x.status==='done').sort((x,y)=>(y.completedAt||'').localeCompare(x.completedAt||'')),today=a.filter(x=>isToday(x.completedAt));$('#doneSummary').innerHTML=`<div class="done-summary-card"><div><div class="hero-kicker">TODAY DONE</div><div class="done-big">${today.length}</div><p>오늘 ${today.length}개를 끝냈어요.</p></div><div class="done-check">✓</div></div>`;$('#doneList').innerHTML=a.map(x=>card(x,'done')).join('');$('#doneCount').textContent=`전체 ${a.length}개 완료`;$('#doneEmpty').classList.toggle('hidden',a.length>0);bindActions('#doneList')}
function renderPresets(){$$('.preset').forEach(p=>p.classList.toggle('active',+p.dataset.min===state.focusMinutes))} function switchView(n){$$('.tab').forEach(t=>t.classList.toggle('active',t.dataset.view===n));$$('.view').forEach(v=>v.classList.remove('active'));$(`#view-${n}`).classList.add('active');if(n==='now')renderNow();if(n==='today')renderToday()}
$$('.tab').forEach(t=>t.onclick=()=>switchView(t.dataset.view));$$('[data-go]').forEach(b=>b.onclick=()=>switchView(b.dataset.go));
$('#quickNoteBtn').onclick=()=>{$('#noteText').value='';$('#noteDialog').showModal();setTimeout(()=>$('#noteText').focus(),30)};$('#saveNoteBtn').onclick=e=>{e.preventDefault();const v=$('#noteText').value.trim();if(!v)return;addItem({title:autoTitle(v,'note'),body:v});$('#noteDialog').close();toast('Inbox에 저장했어요.')};
$('#imageInput').onchange=async e=>{pendingImages=[];for(const f of [...e.target.files])pendingImages.push({name:f.name,data:await fileToDataUrl(f)});e.target.value='';showNextImageWhy()};function fileToDataUrl(f){return new Promise((r,j)=>{const x=new FileReader;x.onload=()=>r(x.result);x.onerror=j;x.readAsDataURL(f)})} function showNextImageWhy(){if(!pendingImages.length)return;const p=pendingImages[0];$('#imageWhyPreview').src=p.data;$('#imageWhyText').value='';$('#imageWhyDialog').showModal();setTimeout(()=>$('#imageWhyText').focus(),30)} function savePendingImage(withMemo){const p=pendingImages.shift(),m=withMemo?$('#imageWhyText').value.trim():'';addItem({type:'image',title:m||p.name.replace(/\.[^.]+$/,''),body:m,image:p.data});$('#imageWhyDialog').close();if(pendingImages.length)showNextImageWhy();else toast('스크린샷을 Inbox에 저장했어요.')} $('#saveImageWhyBtn').onclick=()=>savePendingImage(true);$('#saveImageNoMemoBtn').onclick=()=>savePendingImage(false);
$('#sortBtn').onclick=()=>{state.sort=state.sort==='desc'?'asc':'desc';$('#sortBtn').textContent=state.sort==='desc'?'최신순':'오래된순';saveState();renderInbox()};
function showRecommendations(){const a=state.items.filter(x=>x.status==='inbox'&&(x.kind==='task'||x.kind==='unclassified')).sort(scoreSort).slice(0,3);if(!a.length){toast('추천할 Inbox 항목이 없어요.');return}$('#recommendList').innerHTML=a.map((x,i)=>`<div class="recommend-card"><div class="rank">${['🥇','🥈','🥉'][i]}</div><div><strong>${esc(x.title)}</strong><p>${x.when==='today'?'오늘 하기로 한 일':x.nextAction?'첫 행동이 정해진 일':'오래된 항목부터 가볍게 골랐어요.'}</p></div><button type="button" class="primary-btn" data-rec="${x.id}">시작</button></div>`).join('');$$('[data-rec]').forEach(b=>b.onclick=()=>{$('#recommendDialog').close();handleAction(b.dataset.rec,'now')});$('#recommendDialog').showModal()} $('#recommendBtn').onclick=showRecommendations;$('#todayRecommendBtn').onclick=showRecommendations;
$('#nextActionInput').oninput=e=>{const x=state.items.find(z=>z.id===state.nowId);if(x){x.nextAction=e.target.value;saveState()}};$('#thoughtBtn').onclick=()=>{$('#thoughtText').value='';$('#thoughtDialog').showModal()};$('#saveThoughtBtn').onclick=e=>{e.preventDefault();const v=$('#thoughtText').value.trim();if(!v)return;addItem({title:v,body:v});$('#thoughtDialog').close();switchView('now');toast('생각만 저장하고 돌아왔어요.')};$('#backToInboxBtn').onclick=()=>{const x=state.items.find(z=>z.id===state.nowId);if(!x)return;x.status='inbox';state.nowId=null;resetTimer(false);saveState();render();switchView('inbox')};$('#completeBtn').onclick=()=>{const x=state.items.find(z=>z.id===state.nowId);if(!x)return;x.status='done';x.completedAt=nowIso();state.nowId=null;resetTimer(false);saveState();render();switchView('done');toast('완료! 오늘 해낸 것에 추가했어요.')};
function updateTimerDisplay(){const s=Math.max(0,state.timerRemaining||0);$('#timerDisplay').textContent=`${String(Math.floor(s/60)).padStart(2,'0')}:${String(s%60).padStart(2,'0')}`;$('#timerStart').textContent=state.timerRunning?'⏸ 일시정지':'▶ 시작';$('#timerReset').textContent=`↺ ${state.focusMinutes}분`} function startTimer(){if(state.timerRunning){pauseTimer();return}state.timerRunning=true;state.timerEndsAt=Date.now()+state.timerRemaining*1000;saveState();tickTimer();timerInterval=setInterval(tickTimer,500);updateTimerDisplay()} function tickTimer(){if(!state.timerRunning)return;state.timerRemaining=Math.max(0,Math.ceil((state.timerEndsAt-Date.now())/1000));if(!state.timerRemaining){stopTimer();state.timerRunning=false;state.timerEndsAt=null;saveState();toast('집중 시간이 끝났어요.');}updateTimerDisplay()} function pauseTimer(){state.timerRemaining=Math.max(0,Math.ceil((state.timerEndsAt-Date.now())/1000));state.timerRunning=false;state.timerEndsAt=null;stopTimer();saveState();updateTimerDisplay()} function stopTimer(){if(timerInterval){clearInterval(timerInterval);timerInterval=null}} function resetTimer(s=true){stopTimer();state.timerRunning=false;state.timerEndsAt=null;state.timerRemaining=state.focusMinutes*60;if(s)saveState();updateTimerDisplay()} function resumeTimerIfNeeded(){if(state.timerRunning&&state.timerEndsAt&&!timerInterval)timerInterval=setInterval(tickTimer,500)} $('#timerStart').onclick=startTimer;$('#timerReset').onclick=()=>resetTimer();$$('.preset').forEach(p=>p.onclick=()=>{state.focusMinutes=+p.dataset.min;resetTimer(false);saveState();renderPresets();updateTimerDisplay()});
$('#brainBtn').onclick=()=>{$('#brainText').value='';resetBrain();$('#brainDialog').showModal()};function resetBrain(){if(brainInterval)clearInterval(brainInterval);brainInterval=null;$('#brainTimer').dataset.sec='180';$('#brainTimer').textContent='03:00';$('#brainStartBtn').textContent='▶ 3분 시작'} $('#brainStartBtn').onclick=()=>{if(brainInterval){clearInterval(brainInterval);brainInterval=null;$('#brainStartBtn').textContent='▶ 계속';return}let s=+($('#brainTimer').dataset.sec||180);$('#brainStartBtn').textContent='⏸ 잠깐 멈춤';brainInterval=setInterval(()=>{s--;$('#brainTimer').dataset.sec=s;$('#brainTimer').textContent=`${String(Math.floor(s/60)).padStart(2,'0')}:${String(s%60).padStart(2,'0')}`;if(s<=0){clearInterval(brainInterval);brainInterval=null;$('#brainStartBtn').textContent='끝'}},1000)};$('#saveBrainBtn').onclick=e=>{e.preventDefault();const v=$('#brainText').value.trim();if(!v)return;const lines=v.split(/\n+/).map(s=>s.trim()).filter(Boolean);lines.forEach(line=>addItem({type:'brain',title:line.slice(0,44),body:line}));resetBrain();$('#brainDialog').close();$('#brainResultStats').innerHTML=`<strong>${lines.length}개</strong><span>생각을 Inbox에 안전하게 저장했어요.</span>`;$('#brainResultDialog').showModal()};$('#brainPickBtn').onclick=()=>{$('#brainResultDialog').close();showRecommendations()};
$('#clearDoneBtn').onclick=()=>{if(confirm('완료 기록을 모두 비울까요?')){state.items=state.items.filter(x=>x.status!=='done');saveState();render()}};$('#exportBtn').onclick=()=>{const b=new Blob([JSON.stringify(state,null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(b);a.download=`jjongfocus-backup-${new Date().toISOString().slice(0,10)}.json`;a.click()};$('#importInput').onchange=async e=>{try{state=Object.assign(defaultState(),JSON.parse(await e.target.files[0].text()));state.items=(state.items||[]).map(normalizeItem);saveState();render();toast('복원했어요.')}catch{alert('올바른 백업 파일이 아닙니다.')}e.target.value=''};
if('serviceWorker'in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('./sw.js').catch(()=>{}));window.addEventListener('beforeunload',()=>saveState());render();updateTimerDisplay();
