const $=s=>document.querySelector(s); const $$=s=>[...document.querySelectorAll(s)];
const KEY='jjongfocus_v0_1_state';
let state=loadState();
let timerInterval=null; let brainInterval=null;
function defaultState(){return{items:[],nowId:null,focusMinutes:10,timerRemaining:600,timerRunning:false,timerEndsAt:null,sort:'desc'}}
function loadState(){try{return Object.assign(defaultState(),JSON.parse(localStorage.getItem(KEY)||'{}'))}catch{return defaultState()}}
function saveState(){localStorage.setItem(KEY,JSON.stringify(state));}
function id(){return crypto.randomUUID?crypto.randomUUID():Date.now().toString(36)+Math.random().toString(36).slice(2)}
function esc(s=''){return s.replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]))}
function nowIso(){return new Date().toISOString()}
function fmtDate(iso){return new Intl.DateTimeFormat('ko-KR',{month:'numeric',day:'numeric',hour:'2-digit',minute:'2-digit'}).format(new Date(iso))}
function toast(msg){const t=$('#toast');t.textContent=msg;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),1800)}
function addItem({type='note',title,body='',image=null}){const item={id:id(),type,title:title||autoTitle(body,type),body,image,status:'inbox',createdAt:nowIso(),completedAt:null,nextAction:''};state.items.unshift(item);saveState();render();return item}
function autoTitle(body,type){const clean=(body||'').trim().split(/\n+/)[0].slice(0,44);return clean|| (type==='image'?'스크린샷':'새 메모')}
function render(){renderInbox();renderNow();renderDone();renderPresets()}
function itemMarkup(item,done=false){const visual=item.image?`<img class="thumb" src="${item.image}" alt="스크린샷"/>`:`<div class="item-icon">${item.type==='brain'?'🧠':'✏️'}</div>`;return `<article class="item-card" data-id="${item.id}">${visual}<div><div class="item-title">${esc(item.title)}</div><div class="item-meta">${fmtDate(item.createdAt)}${done&&item.completedAt?' · 완료 '+fmtDate(item.completedAt):''}</div>${item.body?`<div class="item-body">${esc(item.body)}</div>`:''}</div><div class="item-actions">${!done?`<button class="mini-btn now-mini" data-act="now">🔥 NOW</button><button class="mini-btn" data-act="delete">삭제</button>`:`<button class="mini-btn" data-act="restore">복원</button>`}</div></article>`}
function renderInbox(){let items=state.items.filter(x=>x.status==='inbox');items.sort((a,b)=>state.sort==='desc'?b.createdAt.localeCompare(a.createdAt):a.createdAt.localeCompare(b.createdAt));$('#inboxList').innerHTML=items.map(x=>itemMarkup(x)).join('');$('#inboxCount').textContent=`${items.length}개가 기다리고 있어요.`;$('#inboxEmpty').classList.toggle('hidden',items.length>0);$$('#inboxList [data-act]').forEach(b=>b.onclick=()=>handleItemAction(b.closest('[data-id]').dataset.id,b.dataset.act));}
function handleItemAction(itemId,act){const item=state.items.find(x=>x.id===itemId);if(!item)return;if(act==='now'){if(state.nowId&&state.nowId!==itemId){const prev=state.items.find(x=>x.id===state.nowId);if(prev)prev.status='inbox'}state.nowId=itemId;item.status='now';state.timerRemaining=state.focusMinutes*60;state.timerRunning=false;state.timerEndsAt=null;saveState();render();switchView('now');toast('NOW에는 이 일 하나만 둡니다.')}if(act==='delete'){state.items=state.items.filter(x=>x.id!==itemId);saveState();render()}if(act==='restore'){item.status='inbox';item.completedAt=null;saveState();render();}}
function renderNow(){const item=state.items.find(x=>x.id===state.nowId&&x.status==='now');$('#nowEmpty').classList.toggle('hidden',!!item);$('#nowPanel').classList.toggle('hidden',!item);if(!item){stopTimer();return}$('#nowPreview').innerHTML=`<div class="now-card">${item.image?`<img src="${item.image}" alt="현재 작업 스크린샷">`:''}<h2>${esc(item.title)}</h2>${item.body?`<p>${esc(item.body)}</p>`:''}</div>`;$('#nextActionInput').value=item.nextAction||'';resumeTimerIfNeeded();updateTimerDisplay();}
function renderDone(){const items=state.items.filter(x=>x.status==='done').sort((a,b)=>(b.completedAt||'').localeCompare(a.completedAt||''));$('#doneList').innerHTML=items.map(x=>itemMarkup(x,true)).join('');$('#doneCount').textContent=`${items.length}개 완료`;$('#doneEmpty').classList.toggle('hidden',items.length>0);$$('#doneList [data-act]').forEach(b=>b.onclick=()=>handleItemAction(b.closest('[data-id]').dataset.id,b.dataset.act));}
function renderPresets(){$$('.preset').forEach(p=>p.classList.toggle('active',Number(p.dataset.min)===state.focusMinutes))}
function switchView(name){$$('.tab').forEach(t=>t.classList.toggle('active',t.dataset.view===name));$$('.view').forEach(v=>v.classList.remove('active'));$(`#view-${name}`).classList.add('active');if(name==='now')renderNow()}
$$('.tab').forEach(t=>t.onclick=()=>switchView(t.dataset.view));$$('[data-go]').forEach(b=>b.onclick=()=>switchView(b.dataset.go));
$('#quickNoteBtn').onclick=()=>{$('#noteText').value='';$('#noteDialog').showModal();setTimeout(()=>$('#noteText').focus(),50)};
$('#saveNoteBtn').onclick=e=>{e.preventDefault();const v=$('#noteText').value.trim();if(!v)return;addItem({type:'note',title:autoTitle(v,'note'),body:v});$('#noteDialog').close();toast('Inbox에 저장했어요.')};
$('#imageInput').onchange=async e=>{const files=[...e.target.files];for(const file of files){const data=await fileToDataUrl(file);addItem({type:'image',title:file.name.replace(/\.[^.]+$/,''),body:'',image:data})}e.target.value='';toast(`${files.length}장 저장했어요.`)};
function fileToDataUrl(file){return new Promise((res,rej)=>{const r=new FileReader();r.onload=()=>res(r.result);r.onerror=rej;r.readAsDataURL(file)})}
$('#sortBtn').onclick=()=>{state.sort=state.sort==='desc'?'asc':'desc';$('#sortBtn').textContent=state.sort==='desc'?'최신순':'오래된순';saveState();renderInbox()};
$('#nextActionInput').oninput=e=>{const item=state.items.find(x=>x.id===state.nowId);if(item){item.nextAction=e.target.value;saveState()}};
$('#thoughtBtn').onclick=()=>{$('#thoughtText').value='';$('#thoughtDialog').showModal();setTimeout(()=>$('#thoughtText').focus(),50)};
$('#saveThoughtBtn').onclick=e=>{e.preventDefault();const v=$('#thoughtText').value.trim();if(!v)return;addItem({type:'note',title:v,body:v});$('#thoughtDialog').close();switchView('now');toast('생각만 저장하고 현재 작업으로 돌아왔어요.')};
$('#backToInboxBtn').onclick=()=>{const item=state.items.find(x=>x.id===state.nowId);if(!item)return;item.status='inbox';state.nowId=null;resetTimer(false);saveState();render();switchView('inbox');toast('대기로 보냈어요.')};
$('#completeBtn').onclick=()=>{const item=state.items.find(x=>x.id===state.nowId);if(!item)return;item.status='done';item.completedAt=nowIso();state.nowId=null;resetTimer(false);saveState();render();switchView('done');toast('완료! 하나를 끝냈어요.')};
function updateTimerDisplay(){const sec=Math.max(0,state.timerRemaining||0);const m=Math.floor(sec/60),s=sec%60;$('#timerDisplay').textContent=`${String(m).padStart(2,'0')}:${String(s).padStart(2,'0')}`;$('#timerStart').textContent=state.timerRunning?'⏸ 일시정지':'▶ 시작'}
function startTimer(){if(state.timerRunning){pauseTimer();return}state.timerRunning=true;state.timerEndsAt=Date.now()+state.timerRemaining*1000;saveState();tickTimer();timerInterval=setInterval(tickTimer,500);updateTimerDisplay()}
function tickTimer(){if(!state.timerRunning)return;state.timerRemaining=Math.max(0,Math.ceil((state.timerEndsAt-Date.now())/1000));if(state.timerRemaining<=0){stopTimer();state.timerRunning=false;state.timerEndsAt=null;saveState();updateTimerDisplay();toast('집중 시간이 끝났어요. 계속해도 좋아요.');return}updateTimerDisplay()}
function pauseTimer(){if(state.timerRunning){state.timerRemaining=Math.max(0,Math.ceil((state.timerEndsAt-Date.now())/1000))}state.timerRunning=false;state.timerEndsAt=null;stopTimer();saveState();updateTimerDisplay()}
function stopTimer(){if(timerInterval){clearInterval(timerInterval);timerInterval=null}}
function resetTimer(save=true){stopTimer();state.timerRunning=false;state.timerEndsAt=null;state.timerRemaining=state.focusMinutes*60;if(save)saveState();updateTimerDisplay()}
function resumeTimerIfNeeded(){if(state.timerRunning&&state.timerEndsAt){state.timerRemaining=Math.max(0,Math.ceil((state.timerEndsAt-Date.now())/1000));if(state.timerRemaining>0&&!timerInterval){timerInterval=setInterval(tickTimer,500)}else if(state.timerRemaining<=0){state.timerRunning=false;state.timerEndsAt=null;saveState()}}}
$('#timerStart').onclick=startTimer;$('#timerReset').onclick=()=>resetTimer();
$$('.preset').forEach(p=>p.onclick=()=>{state.focusMinutes=Number(p.dataset.min);resetTimer(false);saveState();renderPresets();updateTimerDisplay();toast(`${state.focusMinutes}분으로 설정했어요.`)});
$('#brainBtn').onclick=()=>{$('#brainText').value='';resetBrain();$('#brainDialog').showModal();};
function resetBrain(){if(brainInterval)clearInterval(brainInterval);brainInterval=null;$('#brainTimer').dataset.sec='180';$('#brainTimer').textContent='03:00';$('#brainStartBtn').textContent='▶ 3분 시작'}
$('#brainStartBtn').onclick=()=>{if(brainInterval){clearInterval(brainInterval);brainInterval=null;$('#brainStartBtn').textContent='▶ 계속';return}let sec=Number($('#brainTimer').dataset.sec||180);$('#brainStartBtn').textContent='⏸ 잠깐 멈춤';brainInterval=setInterval(()=>{sec--;$('#brainTimer').dataset.sec=sec;$('#brainTimer').textContent=`${String(Math.floor(sec/60)).padStart(2,'0')}:${String(sec%60).padStart(2,'0')}`;if(sec<=0){clearInterval(brainInterval);brainInterval=null;$('#brainStartBtn').textContent='끝';toast('3분 완료. 이제 Inbox에 넣어두세요.')}},1000);setTimeout(()=>$('#brainText').focus(),30)};
$('#saveBrainBtn').onclick=e=>{e.preventDefault();const v=$('#brainText').value.trim();if(!v)return;const lines=v.split(/\n+/).map(s=>s.trim()).filter(Boolean);if(lines.length>1){lines.forEach(line=>addItem({type:'brain',title:line.slice(0,44),body:line}))}else addItem({type:'brain',title:autoTitle(v,'brain'),body:v});resetBrain();$('#brainDialog').close();switchView('inbox');toast(`${Math.max(1,lines.length)}개를 Inbox에 넣었어요.`)};
$('#clearDoneBtn').onclick=()=>{if(!confirm('완료 기록을 모두 비울까요?'))return;state.items=state.items.filter(x=>x.status!=='done');saveState();renderDone()};
$('#exportBtn').onclick=()=>{const blob=new Blob([JSON.stringify(state,null,2)],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`jjongfocus-backup-${new Date().toISOString().slice(0,10)}.json`;a.click();URL.revokeObjectURL(a.href)};
$('#importInput').onchange=async e=>{const file=e.target.files[0];if(!file)return;try{const data=JSON.parse(await file.text());state=Object.assign(defaultState(),data);saveState();render();toast('백업을 복원했어요.')}catch{alert('올바른 백업 파일이 아닙니다.')}e.target.value=''};
if('serviceWorker'in navigator){window.addEventListener('load',()=>navigator.serviceWorker.register('./sw.js').catch(()=>{}))}
window.addEventListener('beforeunload',()=>{if(state.timerRunning){state.timerRemaining=Math.max(0,Math.ceil((state.timerEndsAt-Date.now())/1000));saveState()}});
render();updateTimerDisplay();
