(()=>{'use strict';
const DB='jjongkeep_simple_v2',STORE='items',LIST_KEY='jjongkeep_lists_v1';
function db(){return new Promise((ok,no)=>{const r=indexedDB.open(DB,1);r.onsuccess=()=>ok(r.result);r.onerror=()=>no(r.error)})}
function rows(d){return new Promise((ok,no)=>{const r=d.transaction(STORE).objectStore(STORE).getAll();r.onsuccess=()=>ok(r.result||[]);r.onerror=()=>no(r.error)})}
async function encode(v){if(v instanceof Blob)return {__damdaBlob:true,type:v.type||'application/octet-stream',bytes:Array.from(new Uint8Array(await v.arrayBuffer()))};if(Array.isArray(v)){const a=[];for(const x of v)a.push(await encode(x));return a}if(v&&typeof v==='object'){const o={};for(const [k,x] of Object.entries(v))o[k]=await encode(x);return o}return v}
function decode(v){if(Array.isArray(v))return v.map(decode);if(v&&typeof v==='object'){if(v.__damdaBlob||v.__photo){return new Blob([new Uint8Array(v.bytes||[])],{type:v.type||'application/octet-stream'})}const o={};for(const [k,x] of Object.entries(v))o[k]=decode(x);return o}return v}
function savedLists(){try{const a=JSON.parse(localStorage.getItem(LIST_KEY)||'[]');return Array.isArray(a)?a:[]}catch{return[]}}
function deriveLists(items){const out=[];for(const i of items){for(const n of Array.isArray(i.lists)?i.lists:[]){if(n&&n!=='할 일'&&!['아이디어','자료'].includes(n)&&!out.includes(n))out.push(n)}if(i.list&&i.list!=='할 일'&&!['아이디어','자료'].includes(i.list)&&!out.includes(i.list))out.push(i.list)}return out}
async function pack(){const d=await db(),src=await rows(d),items=[];for(const x of src)items.push(await encode(x));d.close();return {app:'damda',version:2,createdAt:new Date().toISOString(),itemCount:items.length,lists:savedLists(),items}}
function filename(pre){const d=new Date(),p=n=>String(n).padStart(2,'0');return `${pre}-${d.getFullYear()}${p(d.getMonth()+1)}${p(d.getDate())}-${p(d.getHours())}${p(d.getMinutes())}.json`}
function save(o,pre){const a=document.createElement('a'),u=URL.createObjectURL(new Blob([JSON.stringify(o)],{type:'application/json'}));a.href=u;a.download=filename(pre);a.click();setTimeout(()=>URL.revokeObjectURL(u),1000)}
async function backup(pre='damda-backup'){const o=await pack();save(o,pre);return o}
function valid(o){return !!o&&['damda','jjongkeep'].includes(o.app)&&Array.isArray(o.items)}
async function restore(o){if(!valid(o))throw Error('invalid');const items=o.items.map(decode),d=await db();await new Promise((ok,no)=>{const t=d.transaction(STORE,'readwrite'),s=t.objectStore(STORE);s.clear();items.forEach(x=>s.put(x));t.oncomplete=ok;t.onerror=()=>no(t.error);t.onabort=()=>no(t.error)});const check=await rows(d);d.close();if(check.length!==items.length)throw Error(`restore count mismatch ${check.length}/${items.length}`);const ids=new Set(check.map(x=>String(x.id)));if(items.some(x=>!ids.has(String(x.id))))throw Error('restore id mismatch');const lists=Array.isArray(o.lists)?o.lists:deriveLists(items);localStorage.setItem(LIST_KEY,JSON.stringify(lists));document.dispatchEvent(new Event('jjongkeep:datachanged'));return items.length}
function say(s){const e=document.querySelector('#backupStatus');if(e)e.textContent=s}
function bind(){const p=document.querySelector('#backupPanel'),t=document.querySelector('#backupToggle'),e=document.querySelector('#backupExport'),f=document.querySelector('#backupFile');if(!p||!t||!e||!f)return;t.onclick=()=>p.classList.toggle('hidden');e.onclick=async()=>{try{e.disabled=true;say('백업 중…');const o=await backup();say(`${o.itemCount}개 기록 백업 완료 · 사진·블록·목록 포함`)}catch(x){console.error(x);say('백업 실패')}finally{e.disabled=false}};f.onchange=async()=>{const q=f.files[0];f.value='';if(!q)return;try{const o=JSON.parse(await q.text());if(!valid(o))throw Error('invalid');if(!confirm(`${o.items.length}개 기록 상태로 정확히 복원할까요?\n현재 자료는 먼저 안전백업합니다.`))return;say('현재 자료 안전백업 중…');await backup('damda-before-restore');say('복원 중…');const n=await restore(o);say(`${n}개 복원 완료 · 확인 후 새로고침합니다.`);setTimeout(()=>location.reload(),700)}catch(x){console.error(x);say('올바른 담다 백업 파일인지 확인해주세요.')}}}
document.readyState==='loading'?document.addEventListener('DOMContentLoaded',bind):bind();
})();