(()=>{'use strict';
const DB='jjongkeep_simple_v2',STORE='items',KEY='jjongkeep_lists_v1',BASE=['할 일','아이디어','자료'];const $=s=>document.querySelector(s);let rows=[];const uid=()=>crypto.randomUUID?crypto.randomUUID():Date.now().toString(36)+Math.random().toString(36).slice(2);
function put(i){return new Promise((res,rej)=>{const r=indexedDB.open(DB,1);r.onsuccess=()=>{const q=r.result.transaction(STORE,'readwrite').objectStore(STORE).put(i);q.onsuccess=()=>res();q.onerror=()=>rej(q.error)};r.onerror=()=>rej(r.error)})}
function names(){let a=[];try{a=JSON.parse(localStorage.getItem(KEY)||'[]')}catch{}return [...new Set([...BASE,...a.map(x=>String(x).trim()).filter(Boolean)])]}
function saveName(n){if(!n||BASE.includes(n))return;let a=[];try{a=JSON.parse(localStorage.getItem(KEY)||'[]')}catch{}if(!a.includes(n)){a.push(n);localStorage.setItem(KEY,JSON.stringify(a))}}
function open(){rows=[];$('#brainDumpInput').value='';$('#brainDumpWrite').classList.remove('hidden');$('#brainDumpSort').classList.add('hidden');$('#brainDump').classList.remove('hidden');document.body.style.overflow='hidden';setTimeout(()=>$('#brainDumpInput').focus(),80)}function close(){$('#brainDump').classList.add('hidden');document.body.style.overflow=''}
function split(){const lines=$('#brainDumpInput').value.split(/\n+/).map(x=>x.trim()).filter(Boolean);if(!lines.length)return;rows=lines.map(text=>({text,lists:[],today:false,priority:'normal',skip:false}));$('#brainDumpWrite').classList.add('hidden');$('#brainDumpSort').classList.remove('hidden');paint()}
function picker(n){const r=rows[n],overlay=document.createElement('div');overlay.className='brain-list-picker';const sheet=document.createElement('div');sheet.className='brain-list-sheet';sheet.innerHTML='<div class="brain-list-head"><strong>📁 목록 선택 <small>여러 개 선택 가능</small></strong><button>✕</button></div><div class="brain-list-options"></div><button class="brain-list-new">＋ 새 목록 만들기</button><button class="brain-list-done">선택 완료</button>';overlay.appendChild(sheet);document.body.appendChild(overlay);let pending=[...r.lists];const draw=()=>{const box=sheet.querySelector('.brain-list-options');box.innerHTML='';names().forEach(name=>{const b=document.createElement('button');b.className='brain-list-option'+(pending.includes(name)?' active':'');b.textContent=(name==='할 일'?'✓ ':name==='아이디어'?'💡 ':name==='자료'?'📚 ':'📁 ')+name;b.onclick=()=>{pending=pending.includes(name)?pending.filter(x=>x!==name):[...pending,name];draw()};box.appendChild(b)})};draw();sheet.querySelector('.brain-list-head button').onclick=()=>overlay.remove();overlay.onclick=e=>{if(e.target===overlay)overlay.remove()};sheet.querySelector('.brain-list-new').onclick=()=>{const v=prompt('새 목록 이름을 입력하세요.')?.trim();if(!v)return;saveName(v);if(!pending.includes(v))pending.push(v);draw()};sheet.querySelector('.brain-list-done').onclick=()=>{r.lists=pending;overlay.remove();paint()}}
function paint(){const box=$('#brainDumpRows');box.innerHTML='';rows.forEach((r,n)=>{const task=r.lists.includes('할 일'),el=document.createElement('div');el.className='brain-row'+(r.skip?' skipped':'');el.innerHTML=`<div class="brain-row-text"></div><button class="brain-list-btn${r.lists.length?' active':''}">${r.lists.length?r.lists.map(x=>x==='할 일'?'✓ 할 일':x==='아이디어'?'💡 아이디어':x==='자료'?'📚 자료':'📁 '+x).join(' · '):'📁 목록 선택'}</button><div class="brain-row-extra${task?'':' hidden'}"><button data-p="top">🔥 최우선</button><button data-p="important">⭐ 중요</button><button data-p="normal">○ 보통</button><button data-today>오늘로</button></div><button class="brain-skip">${r.skip?'↩ 다시 넣기':'나중에'}</button>`;el.querySelector('.brain-row-text').textContent=r.text;el.querySelector('.brain-list-btn').onclick=()=>picker(n);el.querySelectorAll('[data-p]').forEach(b=>{b.classList.toggle('active',r.priority===b.dataset.p);b.onclick=()=>{r.priority=b.dataset.p;paint()}});const t=el.querySelector('[data-today]');if(t){t.classList.toggle('active',r.today);t.onclick=()=>{r.today=!r.today;paint()}}el.querySelector('.brain-skip').onclick=()=>{r.skip=!r.skip;paint()};box.appendChild(el)})}
async function save(){const keep=rows.filter(r=>!r.skip);if(!keep.length){close();return}const now=Date.now();for(let n=0;n<keep.length;n++){const r=keep[n],task=r.lists.includes('할 일');r.lists.forEach(saveName);await put({id:uid(),text:r.text,photos:[],lists:r.lists,list:r.lists.find(x=>!BASE.includes(x))||'',type:task?'task':r.lists.includes('아이디어')?'idea':'reference',today:task&&!!r.today,todayOrder:task&&r.today?now+n:null,priority:task?r.priority:undefined,archived:false,completed:false,source:'direct',createdAt:now+n,updatedAt:now+n})}close();location.reload()}
function init(){const btn=$('#brainDumpOpen');if(!btn)return;btn.onclick=open;$('#brainDumpClose').onclick=close;$('#brainDumpNext').onclick=split;$('#brainDumpBack').onclick=()=>{$('#brainDumpSort').classList.add('hidden');$('#brainDumpWrite').classList.remove('hidden')};$('#brainDumpSave').onclick=save;$('#brainDump').onclick=e=>{if(e.target.id==='brainDump')close()}}
document.readyState==='loading'?document.addEventListener('DOMContentLoaded',init):init();})();