(()=>{'use strict';
const DB='jjongkeep_simple_v2',STORE='items',LISTKEY='jjongkeep_lists_v1';const $=s=>document.querySelector(s);let rows=[];
const uid=()=>crypto.randomUUID?crypto.randomUUID():Date.now().toString(36)+Math.random().toString(36).slice(2);
function put(i){return new Promise((res,rej)=>{const r=indexedDB.open(DB,1);r.onsuccess=()=>{const q=r.result.transaction(STORE,'readwrite').objectStore(STORE).put(i);q.onsuccess=()=>res();q.onerror=()=>rej(q.error)};r.onerror=()=>rej(r.error)})}
function listNames(){let a=[];try{a=JSON.parse(localStorage.getItem(LISTKEY)||'[]')}catch{}return [...new Set(a.map(x=>String(x).trim()).filter(Boolean))].sort((a,b)=>a.localeCompare(b,'ko'))}
function saveListName(n){n=(n||'').trim();if(!n)return;const a=listNames();if(!a.includes(n)){a.push(n);localStorage.setItem(LISTKEY,JSON.stringify(a))}}
function open(){rows=[];$('#brainDumpInput').value='';$('#brainDumpWrite').classList.remove('hidden');$('#brainDumpSort').classList.add('hidden');$('#brainDump').classList.remove('hidden');document.body.style.overflow='hidden';setTimeout(()=>$('#brainDumpInput').focus(),80)}
function close(){$('#brainDump').classList.add('hidden');document.body.style.overflow=''}
function split(){const lines=$('#brainDumpInput').value.split(/\n+/).map(x=>x.trim()).filter(Boolean);if(!lines.length)return;rows=lines.map(text=>({text,type:'reference',today:false,priority:null,skip:false,list:''}));$('#brainDumpWrite').classList.add('hidden');$('#brainDumpSort').classList.remove('hidden');paint()}
function chooseList(n){const ns=listNames(),current=rows[n].list||'';const overlay=document.createElement('div');overlay.className='brain-list-picker';const sheet=document.createElement('div');sheet.className='brain-list-sheet';sheet.innerHTML='<div class="brain-list-head"><strong>📁 목록 선택</strong><button type="button">✕</button></div><div class="brain-list-options"></div><button type="button" class="brain-list-new">＋ 새 목록 만들기</button>'+(current?'<button type="button" class="brain-list-clear">목록 해제</button>':'');overlay.appendChild(sheet);document.body.appendChild(overlay);const done=v=>{rows[n].list=v;overlay.remove();paint()};sheet.querySelector('.brain-list-head button').onclick=()=>overlay.remove();overlay.onclick=e=>{if(e.target===overlay)overlay.remove()};const box=sheet.querySelector('.brain-list-options');if(!ns.length){const p=document.createElement('div');p.className='brain-list-empty';p.textContent='아직 만든 목록이 없어요.';box.appendChild(p)}ns.forEach(name=>{const b=document.createElement('button');b.type='button';b.className='brain-list-option'+(current===name?' active':'');b.textContent='📁 '+name;b.onclick=()=>done(name);box.appendChild(b)});sheet.querySelector('.brain-list-new').onclick=()=>{const name=prompt('새 목록 이름을 입력하세요.');if(!name?.trim())return;saveListName(name.trim());done(name.trim())};const clear=sheet.querySelector('.brain-list-clear');if(clear)clear.onclick=()=>done('')}
function paint(){const box=$('#brainDumpRows');box.innerHTML='';rows.forEach((r,n)=>{const el=document.createElement('div');el.className='brain-row'+(r.skip?' skipped':'');el.innerHTML=`<div class="brain-row-text"></div><div class="brain-row-types"><button data-t="task">✓ 할 일</button><button data-t="idea">💡 아이디어</button><button data-t="reference">📚 자료</button><button data-t="skip">나중에</button></div><div class="brain-row-extra hidden"><button data-p="top">🔥 최우선</button><button data-p="important">⭐ 중요</button><button data-p="normal">○ 보통</button><button data-today>오늘로</button></div><button type="button" class="brain-list-btn${r.list?' active':''}">${r.list?'📁 '+r.list:'📁 목록 선택'}</button>`;el.querySelector('.brain-row-text').textContent=r.text;el.querySelectorAll('[data-t]').forEach(b=>{const t=b.dataset.t;b.classList.toggle('active',t==='skip'?r.skip:!r.skip&&r.type===t);b.onclick=()=>{if(t==='skip'){r.skip=!r.skip}else{r.skip=false;r.type=t;if(t!=='task')r.priority=null}paint()}});const extra=el.querySelector('.brain-row-extra');extra.classList.toggle('hidden',r.type!=='task'||r.skip);extra.querySelectorAll('[data-p]').forEach(b=>{b.classList.toggle('active',r.priority===b.dataset.p);b.onclick=()=>{r.priority=b.dataset.p;paint()}});const today=extra.querySelector('[data-today]');today.classList.toggle('active',r.today);today.onclick=()=>{r.today=!r.today;paint()};el.querySelector('.brain-list-btn').onclick=()=>chooseList(n);box.appendChild(el)})}
async function save(){const keep=rows.filter(r=>!r.skip);if(!keep.length){close();return}const now=Date.now();for(let n=0;n<keep.length;n++){const r=keep[n];await put({id:uid(),text:r.text,photos:[],type:r.type,today:!!r.today,todayOrder:r.today?now+n:null,priority:r.type==='task'?(r.priority||'normal'):undefined,list:r.list||'',archived:false,completed:false,source:'direct',createdAt:now+n,updatedAt:now+n})}close();location.reload()}
function init(){const btn=$('#brainDumpOpen');if(!btn)return;btn.onclick=open;$('#brainDumpClose').onclick=close;$('#brainDumpNext').onclick=split;$('#brainDumpBack').onclick=()=>{$('#brainDumpSort').classList.add('hidden');$('#brainDumpWrite').classList.remove('hidden')};$('#brainDumpSave').onclick=save;$('#brainDump').onclick=e=>{if(e.target.id==='brainDump')close()}}
document.readyState==='loading'?document.addEventListener('DOMContentLoaded',init):init();})();