(()=>{'use strict';
const VERSION='v0.1.8';
const CAL_KEY='jjongfocus_calendar_v1',TASK_KEY='jjongfocus_v0_1_state',DB='jjongfocus_diary_db_v1';
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
let selected=dayKey(new Date()),month=new Date(new Date().getFullYear(),new Date().getMonth(),1);
function dayKey(d){return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`}
function parseDay(s){const [y,m,d]=s.split('-').map(Number);return new Date(y,m-1,d)}
function fmt(s){return new Intl.DateTimeFormat('ko-KR',{year:'numeric',month:'long',day:'numeric',weekday:'long'}).format(parseDay(s))}
function esc(s=''){return String(s).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]))}
function uid(){return crypto.randomUUID?crypto.randomUUID():Date.now().toString(36)+Math.random().toString(36).slice(2)}
function calState(){try{return Object.assign({events:[],taskDates:{}},JSON.parse(localStorage.getItem(CAL_KEY)||'{}'))}catch{return{events:[],taskDates:{}}}}
function saveCal(s){localStorage.setItem(CAL_KEY,JSON.stringify(s))}
function taskState(){try{return JSON.parse(localStorage.getItem(TASK_KEY)||'{}')}catch{return{items:[]}}}
function today(){return dayKey(new Date())}
function inject(){
 document.title=`쫑포커스 ${VERSION}`;const ver=$('.topbar h1 span');if(ver)ver.textContent=VERSION;
 const tabs=$('.tabs');if(!tabs||$('[data-view="calendar"]'))return;
 const btn=document.createElement('button');btn.className='tab';btn.dataset.view='calendar';btn.textContent='📅 달력';
 const inbox=$('[data-view="inbox"]');inbox.insertAdjacentElement('afterend',btn);
 const section=document.createElement('section');section.id='view-calendar';section.className='view';section.innerHTML=`<div class="cal-shell"><div class="cal-head"><div><div class="hero-kicker">LIFE CALENDAR</div><h2>📅 달력</h2><p>일정·할 일·기록·완료를 날짜별로 한눈에 봐요.</p></div><button id="calTodayBtn" class="ghost-btn">오늘</button></div><div class="cal-layout"><aside class="cal-card"><div class="cal-nav"><button id="calPrev" class="icon-btn">‹</button><strong id="calTitle"></strong><button id="calNext" class="icon-btn">›</button></div><div class="cal-week"><span>일</span><span>월</span><span>화</span><span>수</span><span>목</span><span>금</span><span>토</span></div><div id="calGrid" class="cal-grid"></div></aside><div class="cal-day-panel"><div class="cal-day-title"><div><div class="hero-kicker">SELECTED DAY</div><h2 id="calDayTitle"></h2></div><div id="calSummary" class="cal-summary"></div></div><div class="cal-quick"><input id="calQuickText" placeholder="할 일이나 일정을 바로 추가하세요"><select id="calQuickType"><option value="task">✅ 할 일</option><option value="event">📅 일정</option></select><input id="calQuickTime" type="time"><button id="calQuickAdd" class="primary-btn">＋ 추가</button></div><div class="cal-sections"><div class="cal-section"><div class="cal-section-title">✅ 할 일 <span id="calTaskCount"></span></div><div id="calTasks" class="cal-list"></div></div><div class="cal-section"><div class="cal-section-title">📅 일정 <span id="calEventCount"></span></div><div id="calEvents" class="cal-list"></div></div><div class="cal-section"><div class="cal-section-title">📖 기록 <span id="calRecordCount"></span></div><div id="calRecords" class="cal-list"></div></div><div class="cal-section"><div class="cal-section-title">✅ 완료 <span id="calDoneCount"></span></div><div id="calDone" class="cal-list"></div></div></div></div></div></div>`;
 const todaySec=$('#view-today');todaySec.parentNode.insertBefore(section,todaySec);
 const st=document.createElement('style');st.textContent=`.cal-shell{display:grid;gap:16px}.cal-head{display:flex;justify-content:space-between;align-items:flex-start;gap:12px}.cal-head h2{margin:3px 0}.cal-head p{margin:0;color:#6b7280}.cal-layout{display:grid;grid-template-columns:minmax(290px,360px) minmax(0,1fr);gap:18px}.cal-card,.cal-day-panel{background:#fff;border:1px solid #e5e7eb;border-radius:22px;padding:16px;box-shadow:0 8px 24px rgba(17,24,39,.04)}.cal-nav{display:flex;align-items:center;justify-content:space-between;margin-bottom:10px}.cal-week,.cal-grid{display:grid;grid-template-columns:repeat(7,1fr);gap:5px}.cal-week span{text-align:center;font-size:11px;color:#8a9099;font-weight:800;padding:5px 0}.cal-day{position:relative;min-height:58px;border:0;border-radius:14px;background:#f7f8fa;padding:7px;text-align:left;cursor:pointer}.cal-day.out{opacity:.38}.cal-day.today{outline:2px solid #111827}.cal-day.selected{background:#111827;color:#fff}.cal-day-num{font-weight:850}.cal-dots{position:absolute;left:7px;right:7px;bottom:6px;display:flex;gap:3px;flex-wrap:wrap}.cal-dot{height:5px;min-width:10px;border-radius:99px;background:currentColor;opacity:.45}.cal-dot.task{width:18px}.cal-dot.event{width:12px}.cal-dot.record{width:8px}.cal-day-title{display:flex;justify-content:space-between;gap:12px;align-items:flex-start}.cal-day-title h2{margin:3px 0 12px}.cal-summary{font-size:12px;color:#6b7280;font-weight:800}.cal-quick{display:grid;grid-template-columns:minmax(0,1fr) 110px 100px auto;gap:8px;margin-bottom:18px}.cal-quick input,.cal-quick select{border:1px solid #dfe3e8;border-radius:12px;padding:11px 12px;background:#fff}.cal-sections{display:grid;gap:12px}.cal-section{border:1px solid #eceff2;border-radius:16px;padding:13px}.cal-section-title{font-weight:900;margin-bottom:8px}.cal-section-title span{font-size:11px;color:#8a9099}.cal-list{display:grid;gap:7px}.cal-row{display:flex;align-items:center;gap:9px;padding:9px 10px;border-radius:12px;background:#f7f8fa}.cal-row-main{min-width:0;flex:1}.cal-row-title{font-size:13px;font-weight:800;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.cal-row-meta{font-size:11px;color:#8a9099;margin-top:2px}.cal-row button{border:0;background:#fff;border-radius:9px;padding:6px 8px;font-size:11px;font-weight:800;cursor:pointer}.cal-empty{font-size:12px;color:#9aa0a8;padding:4px}.cal-record-open{width:100%}@media(max-width:820px){.cal-layout{grid-template-columns:1fr}.cal-quick{grid-template-columns:1fr 1fr}.cal-quick .primary-btn{grid-column:1/-1}.cal-day{min-height:52px;padding:6px}}`;document.head.appendChild(st);
 bind();renderAll();
}
function bind(){
 $('[data-view="calendar"]').onclick=()=>switchCal();
 $('#calPrev').onclick=()=>{month=new Date(month.getFullYear(),month.getMonth()-1,1);renderAll()};
 $('#calNext').onclick=()=>{month=new Date(month.getFullYear(),month.getMonth()+1,1);renderAll()};
 $('#calTodayBtn').onclick=()=>{const d=new Date;selected=dayKey(d);month=new Date(d.getFullYear(),d.getMonth(),1);renderAll()};
 $('#calQuickAdd').onclick=addQuick;$('#calQuickText').addEventListener('keydown',e=>{if(e.key==='Enter'){e.preventDefault();addQuick()}});
}
function switchCal(){ $$('.tab').forEach(t=>t.classList.toggle('active',t.dataset.view==='calendar'));$$('.view').forEach(v=>v.classList.remove('active'));$('#view-calendar').classList.add('active');renderAll() }
async function recordCounts(){return new Promise(ok=>{const r=indexedDB.open(DB,2);r.onsuccess=()=>{const d=r.result;if(!d.objectStoreNames.contains('records')){d.close();ok({});return}const q=d.transaction('records').objectStore('records').getAll();q.onsuccess=()=>{const c={};for(const x of q.result||[])c[x.date]=(c[x.date]||0)+1;d.close();ok(c)};q.onerror=()=>{d.close();ok({})}};r.onerror=()=>ok({});r.onupgradeneeded=()=>{}})}
function taskDateMap(){const c=calState(),s=taskState(),out={};for(const x of s.items||[]){let d=c.taskDates?.[x.id]||'';if(!d&&x.when==='today'&&x.status!=='done')d=today();if(!d)continue;(out[d]||(out[d]=[])).push(x)}return out}
function doneMap(){const s=taskState(),out={};for(const x of s.items||[]){if(!x.completedAt)continue;const d=dayKey(new Date(x.completedAt));(out[d]||(out[d]=[])).push(x)}return out}
function eventMap(){const c=calState(),out={};for(const x of c.events||[])(out[x.date]||(out[x.date]=[])).push(x);return out}
async function renderAll(){if(!$('#view-calendar'))return;const [rc]=await Promise.all([recordCounts()]),tm=taskDateMap(),dm=doneMap(),em=eventMap();renderGrid(tm,em,rc,dm);renderDay(tm[selected]||[],em[selected]||[],rc[selected]||0,dm[selected]||[])}
function renderGrid(tm,em,rc,dm){const y=month.getFullYear(),m=month.getMonth();$('#calTitle').textContent=`${y}년 ${m+1}월`;const start=new Date(y,m,1-new Date(y,m,1).getDay()),a=[];for(let i=0;i<42;i++){const d=new Date(start);d.setDate(start.getDate()+i);const k=dayKey(d),tasks=(tm[k]||[]).length,events=(em[k]||[]).length,records=rc[k]||0,done=(dm[k]||[]).length;a.push(`<button class="cal-day${d.getMonth()!==m?' out':''}${k===today()?' today':''}${k===selected?' selected':''}" data-cal-date="${k}"><span class="cal-day-num">${d.getDate()}</span><span class="cal-dots">${tasks?'<i class="cal-dot task"></i>':''}${events?'<i class="cal-dot event"></i>':''}${records?'<i class="cal-dot record"></i>':''}${done?'<i class="cal-dot"></i>':''}</span></button>`)}$('#calGrid').innerHTML=a.join('');$$('[data-cal-date]').forEach(b=>b.onclick=()=>{selected=b.dataset.calDate;const z=parseDay(selected);month=new Date(z.getFullYear(),z.getMonth(),1);renderAll()})}
function renderDay(tasks,events,records,done){$('#calDayTitle').textContent=fmt(selected);$('#calSummary').textContent=`할 일 ${tasks.length} · 일정 ${events.length} · 기록 ${records} · 완료 ${done.length}`;$('#calTaskCount').textContent=`${tasks.length}개`;$('#calEventCount').textContent=`${events.length}개`;$('#calRecordCount').textContent=`${records}개`;$('#calDoneCount').textContent=`${done.length}개`;
 $('#calTasks').innerHTML=tasks.length?tasks.map(x=>`<div class="cal-row"><div>✅</div><div class="cal-row-main"><div class="cal-row-title">${esc(x.title)}</div><div class="cal-row-meta">${x.nextAction?'첫 행동 · '+esc(x.nextAction):'Inbox와 연결된 할 일'}</div></div><button data-cal-start="${x.id}">NOW</button></div>`).join(''):'<div class="cal-empty">이 날의 할 일이 없어요.</div>';
 $('#calEvents').innerHTML=events.length?events.sort((a,b)=>(a.time||'99:99').localeCompare(b.time||'99:99')).map(x=>`<div class="cal-row"><div>📅</div><div class="cal-row-main"><div class="cal-row-title">${esc(x.title)}</div><div class="cal-row-meta">${x.time||'시간 미정'}</div></div><button data-del-event="${x.id}">삭제</button></div>`).join(''):'<div class="cal-empty">이 날의 일정이 없어요.</div>';
 $('#calRecords').innerHTML=records?`<button class="ghost-btn cal-record-open" id="calOpenRecords">📖 ${records}개의 기록 보기</button>`:'<div class="cal-empty">이 날의 기록이 없어요.</div>';
 $('#calDone').innerHTML=done.length?done.map(x=>`<div class="cal-row"><div>✓</div><div class="cal-row-main"><div class="cal-row-title">${esc(x.title)}</div><div class="cal-row-meta">완료됨</div></div></div>`).join(''):'<div class="cal-empty">이 날 완료한 일이 없어요.</div>';
 $$('[data-cal-start]').forEach(b=>b.onclick=()=>{try{if(typeof handleAction==='function')handleAction(b.dataset.calStart,'now')}catch{} });$$('[data-del-event]').forEach(b=>b.onclick=()=>{const c=calState();c.events=(c.events||[]).filter(x=>x.id!==b.dataset.delEvent);saveCal(c);renderAll()});if($('#calOpenRecords'))$('#calOpenRecords').onclick=()=>{const t=$('[data-view="diary"]');if(t)t.click()};
}
function addQuick(){const input=$('#calQuickText'),title=input.value.trim();if(!title)return;const type=$('#calQuickType').value,time=$('#calQuickTime').value,c=calState();if(type==='event'){c.events.push({id:uid(),title,date:selected,time,createdAt:new Date().toISOString()});saveCal(c)}else{try{if(typeof addItem==='function'){const x=addItem({title,body:title});x.kind='task';x.when=selected===today()?'today':'';if(typeof saveState==='function')saveState();if(typeof render==='function')render();c.taskDates[x.id]=selected;saveCal(c)}else{throw new Error('bridge')}}catch{alert('할 일 연결에 실패했어요. 새로고침 후 다시 시도해주세요.');return}}input.value='';$('#calQuickTime').value='';renderAll()}
const ready=()=>{inject();};if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',ready);else ready();
})();