(()=>{'use strict';
const DB='jjongkeep_simple_v2',STORE='items';const $=s=>document.querySelector(s);let urls=[];
function open(){return new Promise((res,rej)=>{const r=indexedDB.open(DB,1);r.onsuccess=()=>res(r.result);r.onerror=()=>rej(r.error)})}
async function all(){const db=await open();return new Promise((res,rej)=>{const q=db.transaction(STORE).objectStore(STORE).getAll();q.onsuccess=()=>res(q.result||[]);q.onerror=()=>rej(q.error)})}
async function put(i){const db=await open();return new Promise((res,rej)=>{const q=db.transaction(STORE,'readwrite').objectStore(STORE).put(i);q.onsuccess=()=>res();q.onerror=()=>rej(q.error)})}
async function del(id){const db=await open();return new Promise((res,rej)=>{const q=db.transaction(STORE,'readwrite').objectStore(STORE).delete(id);q.onsuccess=()=>res();q.onerror=()=>rej(q.error)})}
function esc(s=''){return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function cleanup(){urls.forEach(u=>URL.revokeObjectURL(u));urls=[]}
function button(label,cls,fn){const b=document.createElement('button');b.type='button';b.className='pill'+(cls?' '+cls:'');b.textContent=label;b.onclick=fn;return b}
async function restore(i){i.completed=false;i.completedAt=null;i.archived=false;i.today=false;i.updatedAt=Date.now();await put(i);await paint()}
async function remove(i){if(!confirm('이 완료 기록을 완전히 삭제할까요?'))return;await del(i.id);await paint()}
async function paint(){cleanup();const q=($('#search')?.value||'').trim().toLowerCase();let items=(await all()).filter(x=>x.completed&&x.type==='task');if(q)items=items.filter(x=>(x.text||'').toLowerCase().includes(q));items.sort((a,b)=>(b.completedAt||b.updatedAt||0)-(a.completedAt||a.updatedAt||0));const list=$('#list');if(!list)return;list.innerHTML='';items.forEach(i=>{const el=document.createElement('article');el.className='note completed priority-'+(i.priority||'normal');if(i.photos?.length){const ps=document.createElement('div');ps.className='note-photos';i.photos.forEach(p=>{const im=document.createElement('img');const u=URL.createObjectURL(p);urls.push(u);im.src=u;im.alt='완료한 할 일 사진';ps.appendChild(im)});el.appendChild(ps)}const body=document.createElement('div');body.className='note-body';const when=i.completedAt?new Date(i.completedAt).toLocaleString('ko-KR',{month:'numeric',day:'numeric',hour:'2-digit',minute:'2-digit'}):'';body.innerHTML=`<div class="note-text expanded">${esc(i.text||'')}</div><div class="note-source">✓ 완료${when?' · '+when:''}</div>`;const tags=document.createElement('div');tags.className='note-actions';tags.innerHTML=`<span class="pill selected">${(i.priority||'normal')==='top'?'🔥 최우선':i.priority==='important'?'⭐ 중요':'○ 보통'}</span>${i.list?`<span class="pill selected">📁 ${esc(i.list)}</span>`:''}`;body.appendChild(tags);const actions=document.createElement('div');actions.className='note-actions';actions.appendChild(button('↩ 되돌리기','',()=>restore(i)));actions.appendChild(button('🗑 삭제','completed-delete',()=>remove(i)));body.appendChild(actions);el.appendChild(body);list.appendChild(el)});const empty=$('#empty');empty.classList.toggle('hidden',items.length>0);if(!items.length){empty.querySelector('strong').textContent='아직 완료한 할 일이 없어요.';empty.querySelector('span').textContent='할 일을 완료하면 여기에 차곡차곡 남아요.'}}
function init(){document.querySelectorAll('.tab').forEach(b=>b.addEventListener('click',()=>{document.body.dataset.view=b.dataset.view||'';if(b.dataset.view==='completed')setTimeout(paint,0)}));const search=$('#search');if(search)search.addEventListener('input',()=>{if(document.body.dataset.view==='completed')setTimeout(paint,0)});document.body.dataset.view=document.querySelector('.tab.active')?.dataset.view||'inbox'}
document.readyState==='loading'?document.addEventListener('DOMContentLoaded',init):init();})();