(()=>{'use strict';
const CLIENT_ID='307014379444-2n5pe3g74jr04tuu7kjdpgesp6e1336t.apps.googleusercontent.com';
const SCOPES='openid email profile https://www.googleapis.com/auth/drive.file';
const DB='jjongkeep_simple_v2',STORE='items',CATKEY='damda_categories_v1',DEVICEKEY='damda_sync_device_v1';
let token='',tokenClient=null;
const uid=()=>Date.now().toString(36)+Math.random().toString(36).slice(2);
function deviceId(){let v=localStorage.getItem(DEVICEKEY);if(!v){v='device-'+uid();localStorage.setItem(DEVICEKEY,v)}return v}
function openDb(){return new Promise((res,rej)=>{const r=indexedDB.open(DB);r.onsuccess=()=>res(r.result);r.onerror=()=>rej(r.error)})}
async function localItems(){const db=await openDb();return new Promise((res,rej)=>{const r=db.transaction(STORE).objectStore(STORE).getAll();r.onsuccess=()=>res(r.result||[]);r.onerror=()=>rej(r.error)})}
async function putLocal(x){const db=await openDb();return new Promise((res,rej)=>{const r=db.transaction(STORE,'readwrite').objectStore(STORE).put(x);r.onsuccess=()=>res();r.onerror=()=>rej(r.error)})}
function categories(){try{return JSON.parse(localStorage.getItem(CATKEY)||'[]')}catch{return[]}}
function withoutBlobs(item){const copy={...item};if(Array.isArray(copy.contentBlocks))copy.contentBlocks=copy.contentBlocks.map(b=>{const x={...b};if(x.blob instanceof Blob){x.hasLocalImage=true;delete x.blob}return x});if(Array.isArray(copy.photos))copy.photos=copy.photos.map(p=>p instanceof Blob?{hasLocalImage:true}:p);return copy}
function initClient(){return new Promise((res,rej)=>{const start=()=>{try{tokenClient=google.accounts.oauth2.initTokenClient({client_id:CLIENT_ID,scope:SCOPES,callback:r=>{if(r.error)return window.dispatchEvent(new CustomEvent('damda-sync-token-error',{detail:r}));token=r.access_token||'';window.dispatchEvent(new CustomEvent('damda-sync-token',{detail:r}))}});res()}catch(e){rej(e)}};if(window.google?.accounts?.oauth2)return start();let n=0;const t=setInterval(()=>{if(window.google?.accounts?.oauth2){clearInterval(t);start()}else if(++n>80){clearInterval(t);rej(new Error('Google Identity Services load timeout'))}},100)})}
async function ensureToken(){if(token)return token;await initClient();return new Promise((res,rej)=>{const ok=e=>{cleanup();res(e.detail.access_token)},bad=e=>{cleanup();rej(new Error(e.detail?.error||'Google login failed'))},cleanup=()=>{removeEventListener('damda-sync-token',ok);removeEventListener('damda-sync-token-error',bad)};addEventListener('damda-sync-token',ok,{once:true});addEventListener('damda-sync-token-error',bad,{once:true});tokenClient.requestAccessToken({prompt:'consent'})})}
async function api(method,body){const t=await ensureToken();const r=await fetch('/api/sync',{method,headers:{authorization:'Bearer '+t,...(body?{'content-type':'application/json'}:{})},body:body?JSON.stringify(body):undefined});if(r.status===401){token='';throw new Error('Google login expired')}if(!r.ok)throw new Error('Sync API '+r.status);return r.json()}
function mergeRemote(local,remote){const l={...local};const rb=Array.isArray(remote.contentBlocks)?remote.contentBlocks:[];if(Array.isArray(l.contentBlocks)&&rb.length){const old=new Map(l.contentBlocks.map(b=>[b.id,b]));l.contentBlocks=rb.map(b=>{const prev=old.get(b.id);return b.hasLocalImage&&prev?.blob instanceof Blob?{...b,blob:prev.blob}:b})}return l}
async function sync(){const id=deviceId(),items=await localItems(),cats=categories();const records=items.map(x=>({id:x.id,data:JSON.stringify(withoutBlobs(x)),updated_at:Number(x.updatedAt||x.createdAt||0),deleted:0,device_id:id}));const catRows=cats.map(c=>({id:c.id,name:c.name||'',updated_at:Number(c.updatedAt||0)||Date.now(),deleted:0,device_id:id}));await api('POST',{records,categories:catRows});const remote=await api('GET');const localMap=new Map(items.map(x=>[x.id,x]));let changed=0;for(const row of remote.records||[]){if(row.deleted)continue;let x;try{x=JSON.parse(row.data)}catch{continue}const old=localMap.get(row.id);if(!old||Number(row.updated_at)>Number(old.updatedAt||old.createdAt||0)){await putLocal(old?mergeRemote(old,x):x);changed++}}const currentCats=new Map(cats.map(c=>[c.id,c]));let catsChanged=false;for(const row of remote.categories||[]){if(row.deleted)continue;if(!currentCats.has(row.id)){currentCats.set(row.id,{id:row.id,name:row.name});catsChanged=true}}if(catsChanged)localStorage.setItem(CATKEY,JSON.stringify([...currentCats.values()]));return{changed,user:remote.user||null}}
window.damdaSync={async run(){return sync()},clearToken(){token=''}};
})();
