(()=>{'use strict';
const CLIENT_ID='307014379444-2n5pe3g74jr04tuu7kjdpgesp6e1336t.apps.googleusercontent.com';
const SCOPES='openid email profile https://www.googleapis.com/auth/drive.file';
const DB='jjongkeep_simple_v2',STORE='items',CATKEY='damda_categories_v1',DEVICEKEY='damda_sync_device_v1';
let token='',tokenClient=null;
const uid=()=>Date.now().toString(36)+Math.random().toString(36).slice(2);
function deviceId(){let v=localStorage.getItem(DEVICEKEY);if(!v){v='device-'+uid();localStorage.setItem(DEVICEKEY,v)}return v}
function openDb(){return new Promise((res,rej)=>{const r=indexedDB.open(DB);r.onsuccess=()=>res(r.result);r.onerror=()=>rej(r.error)})}
async function localItems(){const db=await openDb();return new Promise((res,rej)=>{const r=db.transaction(STORE).objectStore(STORE).getAll();r.onsuccess=()=>res(r.result||[]);r.onerror=()=>rej(r.error)})}
async function putLocal(x){const db=await openDb();return new Promise((res,rej)=>{const r=db.transaction(STORE,'readwrite').objectStore(STORE).put(x);r.onsuccess=()=>res();r.onerror=()=>rej(r.error)})}
function categories(){try{return JSON.parse(localStorage.getItem(CATKEY)||'[]')}catch{return[]}}
function initClient(){return new Promise((res,rej)=>{const start=()=>{try{tokenClient=google.accounts.oauth2.initTokenClient({client_id:CLIENT_ID,scope:SCOPES,callback:r=>{if(r.error)return window.dispatchEvent(new CustomEvent('damda-sync-token-error',{detail:r}));token=r.access_token||'';window.dispatchEvent(new CustomEvent('damda-sync-token',{detail:r}))}});res()}catch(e){rej(e)}};if(window.google?.accounts?.oauth2)return start();let n=0;const t=setInterval(()=>{if(window.google?.accounts?.oauth2){clearInterval(t);start()}else if(++n>80){clearInterval(t);rej(new Error('Google Identity Services load timeout'))}},100)})}
async function ensureToken(){if(token)return token;await initClient();return new Promise((res,rej)=>{const ok=e=>{cleanup();res(e.detail.access_token)},bad=e=>{cleanup();rej(new Error(e.detail?.error||'Google login failed'))},cleanup=()=>{removeEventListener('damda-sync-token',ok);removeEventListener('damda-sync-token-error',bad)};addEventListener('damda-sync-token',ok,{once:true});addEventListener('damda-sync-token-error',bad,{once:true});tokenClient.requestAccessToken({prompt:'consent'})})}
async function api(method,body){const t=await ensureToken();const r=await fetch('/api/sync',{method,headers:{authorization:'Bearer '+t,...(body?{'content-type':'application/json'}:{})},body:body?JSON.stringify(body):undefined});if(r.status===401){token='';throw new Error('Google login expired')}if(!r.ok)throw new Error('Sync API '+r.status);return r.json()}
async function driveFetch(url,opt={}){const t=await ensureToken();let r=await fetch(url,{...opt,headers:{...(opt.headers||{}),authorization:'Bearer '+t}});if(r.status===401){token='';const nt=await ensureToken();r=await fetch(url,{...opt,headers:{...(opt.headers||{}),authorization:'Bearer '+nt}})}if(!r.ok)throw new Error('Google Drive '+r.status);return r}
function extFor(type){const t=(type||'').toLowerCase();if(t.includes('png'))return'png';if(t.includes('webp'))return'webp';if(t.includes('gif'))return'gif';if(t.includes('heic'))return'heic';if(t.includes('heif'))return'heif';return'jpg'}
async function uploadImage(blob,name){const boundary='damda_'+uid(),meta=JSON.stringify({name,mimeType:blob.type||'application/octet-stream',appProperties:{app:'damda',kind:'record-image'}}),head='--'+boundary+'\r\nContent-Type: application/json; charset=UTF-8\r\n\r\n'+meta+'\r\n--'+boundary+'\r\nContent-Type: '+(blob.type||'application/octet-stream')+'\r\n\r\n',tail='\r\n--'+boundary+'--';const body=new Blob([head,blob,tail],{type:'multipart/related; boundary='+boundary});const r=await driveFetch('https://www.googleapis.com/upload/drive/v3/files?uploadType=multipart&fields=id,name,mimeType',{method:'POST',headers:{'content-type':'multipart/related; boundary='+boundary},body});return r.json()}
async function downloadImage(ref){const r=await driveFetch('https://www.googleapis.com/drive/v3/files/'+encodeURIComponent(ref.id)+'?alt=media');return r.blob()}
async function serializeItem(item){const copy={...item};if(Array.isArray(item.contentBlocks)){copy.contentBlocks=[];for(const block of item.contentBlocks){const b={...block};if(block.blob instanceof Blob){if(!b.driveImage?.id){const f=await uploadImage(block.blob,'damda-'+item.id+'-'+(block.id||uid())+'.'+extFor(block.blob.type));b.driveImage={id:f.id,type:block.blob.type||f.mimeType||'application/octet-stream'}}delete b.blob;b.hasLocalImage=true}copy.contentBlocks.push(b)}}if(Array.isArray(item.photos)){copy.photos=[];for(let i=0;i<item.photos.length;i++){const p=item.photos[i];if(p instanceof Blob){const f=await uploadImage(p,'damda-'+item.id+'-legacy-'+i+'.'+extFor(p.type));copy.photos.push({driveImage:{id:f.id,type:p.type||f.mimeType||'application/octet-stream'},hasLocalImage:true})}else copy.photos.push(p)}}return copy}
function needsHydration(remote,local){if(Array.isArray(remote.contentBlocks)){const old=new Map((local?.contentBlocks||[]).map(b=>[b.id,b]));if(remote.contentBlocks.some(b=>b?.driveImage?.id&&!(old.get(b.id)?.blob instanceof Blob)))return true}if(Array.isArray(remote.photos)){for(let i=0;i<remote.photos.length;i++)if(remote.photos[i]?.driveImage?.id&&!(local?.photos?.[i] instanceof Blob))return true}return false}
async function hydrateRemote(remote,local){const out={...remote};const oldBlocks=new Map((local?.contentBlocks||[]).map(b=>[b.id,b]));if(Array.isArray(remote.contentBlocks)){out.contentBlocks=[];for(const b0 of remote.contentBlocks){const b={...b0},prev=oldBlocks.get(b.id);if(prev?.blob instanceof Blob)b.blob=prev.blob;else if(b.driveImage?.id){try{b.blob=await downloadImage(b.driveImage)}catch(e){console.warn('Damda image download failed',e)}}out.contentBlocks.push(b)}}if(Array.isArray(remote.photos)){out.photos=[];for(let i=0;i<remote.photos.length;i++){const p=remote.photos[i],old=local?.photos?.[i];if(old instanceof Blob)out.photos.push(old);else if(p?.driveImage?.id){try{out.photos.push(await downloadImage(p.driveImage))}catch(e){console.warn('Damda legacy image download failed',e);out.photos.push(p)}}else out.photos.push(p)}}return out}
async function sync(){const id=deviceId(),items=await localItems(),cats=categories(),records=[];for(const x of items){const data=await serializeItem(x);records.push({id:x.id,data:JSON.stringify(data),updated_at:Number(x.updatedAt||x.createdAt||0),deleted:0,device_id:id})}const catRows=cats.map(c=>({id:c.id,name:c.name||'',updated_at:Number(c.updatedAt||0)||Date.now(),deleted:0,device_id:id}));await api('POST',{records,categories:catRows});const remote=await api('GET'),localMap=new Map(items.map(x=>[x.id,x]));let changed=0;for(const row of remote.records||[]){if(row.deleted)continue;let x;try{x=JSON.parse(row.data)}catch{continue}const old=localMap.get(row.id),newer=!old||Number(row.updated_at)>Number(old.updatedAt||old.createdAt||0),hydrate=needsHydration(x,old);if(newer||hydrate){x=await hydrateRemote(x,old);await putLocal(x);changed++}}const currentCats=new Map(cats.map(c=>[c.id,c]));let catsChanged=false;for(const row of remote.categories||[]){if(row.deleted)continue;if(!currentCats.has(row.id)){currentCats.set(row.id,{id:row.id,name:row.name});catsChanged=true}}if(catsChanged)localStorage.setItem(CATKEY,JSON.stringify([...currentCats.values()]));return{changed,user:remote.user||null}}
async function runFromMenu(btn){const old=btn.textContent;btn.disabled=true;btn.textContent='동기화 중…';try{const r=await sync();btn.textContent='✓ 동기화 완료';setTimeout(()=>{if(r.changed)location.reload();else{btn.disabled=false;btn.textContent=old}},700)}catch(e){console.error(e);btn.disabled=false;btn.textContent='동기화 실패 · 다시 시도';alert('동기화하지 못했어요. Google 로그인과 배포 상태를 확인해주세요.')}}
function injectMenu(){const menu=document.querySelector('.more-menu');if(!menu||menu.querySelector('#damdaSyncNow'))return;const b=document.createElement('button');b.id='damdaSyncNow';b.type='button';b.textContent='☁ Google 동기화';b.onclick=()=>runFromMenu(b);menu.appendChild(b)}
new MutationObserver(injectMenu).observe(document.documentElement,{childList:true,subtree:true});
window.damdaSync={run:sync,clearToken(){token=''}};
})();
