(()=>{
'use strict';
const q=s=>document.querySelector(s), qa=s=>[...document.querySelectorAll(s)];
const AUTH_KEY='jjongfocus_diary_auth_v1',DB_NAME='jjongfocus_diary_db_v1',TODO_KEY='jjongfocus_v0_1_state';
let key=null,selectedDate=dateKey(new Date()),month=new Date(new Date().getFullYear(),new Date().getMonth(),1),photos=[],mood='',lockTimer=null;
const toast=m=>{const t=q('#toast');if(!t)return;t.textContent=m;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),1800)};
const esc=s=>String(s||'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot',"'":'&#039;'}[c]));
function dateKey(d){return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`}
function auth(){try{return JSON.parse(localStorage.getItem(AUTH_KEY)||'null')}catch{return null}}
function b64(bytes){let s='';bytes.forEach(v=>s+=String.fromCharCode(v));return btoa(s)}
function bytes(s){const x=atob(s),a=new Uint8Array(x.length);for(let i=0;i<x.length;i++)a[i]=x.charCodeAt(i);return a}
async function derive(password,salt){const mat=await crypto.subtle.importKey('raw',new TextEncoder().encode(password),'PBKDF2',false,['deriveKey']);return crypto.subtle.deriveKey({name:'PBKDF2',salt,iterations:150000,hash:'SHA-256'},mat,{name:'AES-GCM',length:256},false,['encrypt','decrypt'])}
async function encrypt(k,obj){const iv=crypto.getRandomValues(new Uint8Array(12)),plain=new TextEncoder().encode(JSON.stringify(obj)),cipher=await crypto.subtle.encrypt({name:'AES-GCM',iv},k,plain);return{iv:b64(iv),data:b64(new Uint8Array(cipher))}}
async function decrypt(k,p){const plain=await crypto.subtle.decrypt({name:'AES-GCM',iv:bytes(p.iv)},k,bytes(p.data));return JSON.parse(new TextDecoder().decode(plain))}
function db(){return new Promise((resolve,reject)=>{const r=indexedDB.open(DB_NAME,1);r.onupgradeneeded=()=>{if(!r.result.objectStoreNames.contains('entries'))r.result.createObjectStore('entries',{keyPath:'date'})};r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error)})}
async function put(date,payload){const d=await db();return new Promise((resolve,reject)=>{const tx=d.transaction('entries','readwrite');tx.objectStore('entries').put({date,payload});tx.oncomplete=()=>{d.close();resolve()};tx.onerror=()=>{d.close();reject(tx.error)}})}
async function get(date){const d=await db();return new Promise((resolve,reject)=>{const tx=d.transaction('entries','readonly'),r=tx.objectStore('entries').get(date);r.onsuccess=()=>{d.close();resolve(r.result||null)};r.onerror=()=>{d.close();reject(r.error)}})}
async function del(date){const d=await db();return new Promise((resolve,reject)=>{const tx=d.transaction('entries','readwrite');tx.objectStore('entries').delete(date);tx.oncomplete=()=>{d.close();resolve()};tx.onerror=()=>{d.close();reject(tx.error)}})}
async function dates(){const d=await db();return new Promise((resolve,reject)=>{const tx=d.transaction('entries','readonly'),r=tx.objectStore('entries').getAllKeys();r.onsuccess=()=>{d.close();resolve(r.result||[])};r.onerror=()=>{d.close();reject(r.error)}})}
function resetLock(){clearTimeout(lockTimer);if(key)lockTimer=setTimeout(()=>{key=null;updateGate();toast('보호를 위해 일기를 자동으로 잠갔어요.')},10*60*1000)}
async function setup(password){const salt=crypto.getRandomValues(new Uint8Array(16)),k=await derive(password,salt),verifier=await encrypt(k,{ok:'jjongfocus-diary'});localStorage.setItem(AUTH_KEY,JSON.stringify({salt:b64(salt),verifier,version:1}));key=k;resetLock()}
async function unlock(password){const a=auth();if(!a)return false;try{const k=await derive(password,bytes(a.salt)),v=await decrypt(k,a.verifier);if(v.ok!=='jjongfocus-diary')return false;key=k;resetLock();return true}catch{return false}}
function lock(){key=null;photos=[];mood='';clearTimeout(lockTimer);updateGate();toast('일기를 잠갔어요.')}
function updateGate(){const has=!!auth(),open=!!key;q('#diaryLocked').classList.toggle('hidden',open);q('#diaryContent').classList.toggle('hidden',!open);q('#diaryLockText').textContent=has?'비밀번호를 입력하면 오늘의 기록을 볼 수 있어요.':'처음 한 번 비밀번호를 만들면 일기 내용을 암호화해서 저장해요.';q('#diaryUnlockBtn').textContent=has?'🔓 비밀번호로 열기':'🔐 비밀번호 만들기'}
function passwordDialog(){const has=!!auth();q('#diaryPasswordTitle').textContent=has?'일기 잠금 해제':'일기 비밀번호 만들기';q('#diaryPasswordHelp').textContent=has?'설정한 비밀번호를 입력하세요.':'4자 이상으로 만들어주세요. 비밀번호를 잊으면 암호화된 일기를 복구하기 어렵습니다.';q('#diaryPasswordInput').value='';q('#diaryPasswordConfirm').value='';q('#diaryPasswordConfirm').classList.toggle('hidden',has);q('#diaryPasswordError').textContent='';q('#diaryPasswordSubmit').textContent=has?'열기':'만들기';q('#diaryPasswordDialog').showModal();setTimeout(()=>q('#diaryPasswordInput').focus(),30)}
function fmt(date){const [y,m,d]=date.split('-').map(Number);return new Intl.DateTimeFormat('ko-KR',{year:'numeric',month:'long',day:'numeric',weekday:'long'}).format(new Date(y,m-1,d))}
function doneFor(date){try{const s=JSON.parse(localStorage.getItem(TODO_KEY)||'{}');return(s.items||[]).filter(x=>x.status==='done'&&x.completedAt&&dateKey(new Date(x.completedAt))===date).map(x=>x.title).slice(0,20)}catch{return[]}}
function doneSnapshot(items=doneFor(selectedDate)){q('#diaryDoneSnapshot').innerHTML=items.length?`<strong>✅ 이 날 완료한 일 · ${items.length}개</strong><ul>${items.map(x=>`<li>${esc(x)}</li>`).join('')}</ul>`:'<strong>✅ 이 날 완료한 일</strong><span>완료 기록이 없어요.</span>'}
function renderPhotos(){q('#diaryPhotos').innerHTML=photos.map((src,i)=>`<div class="diary-photo"><img src="${src}" alt="일기 사진 ${i+1}"><button type="button" data-photo-remove="${i}" aria-label="사진 삭제">×</button></div>`).join('');qa('[data-photo-remove]').forEach(b=>b.onclick=()=>{photos.splice(+b.dataset.photoRemove,1);renderPhotos();resetLock()})}
async function renderCalendar(){if(!key)return;resetLock();const marks=new Set(await dates()),y=month.getFullYear(),m=month.getMonth();q('#calendarTitle').textContent=`${y}년 ${m+1}월`;const first=new Date(y,m,1),start=new Date(y,m,1-first.getDay()),cells=[];for(let i=0;i<42;i++){const d=new Date(start);d.setDate(start.getDate()+i);const k=dateKey(d);cells.push(`<button class="calendar-day${d.getMonth()!==m?' outside':''}${k===dateKey(new Date())?' today':''}${k===selectedDate?' selected':''}${marks.has(k)?' has-entry':''}" data-date="${k}">${d.getDate()}</button>`)}q('#calendarGrid').innerHTML=cells.join('');qa('#calendarGrid [data-date]').forEach(b=>b.onclick=async()=>{selectedDate=b.dataset.date;const [yy,mm]=selectedDate.split('-').map(Number);month=new Date(yy,mm-1,1);await renderCalendar();await openDate(selectedDate)})}
async function openDate(date){if(!key)return;resetLock();selectedDate=date;q('#diaryDateTitle').textContent=fmt(date);q('#diarySavedBadge').classList.add('hidden');mood='';photos=[];q('#diaryText').value='';q('#diaryTags').value='';qa('#moodChoices button').forEach(b=>b.classList.remove('selected'));try{const row=await get(date);if(row){const d=await decrypt(key,row.payload);mood=d.mood||'';photos=[...(d.photos||[])];q('#diaryText').value=d.text||'';q('#diaryTags').value=(d.tags||[]).join(', ');q('#diarySavedBadge').classList.remove('hidden');qa('#moodChoices button').forEach(b=>b.classList.toggle('selected',b.dataset.mood===mood));renderPhotos();doneSnapshot(d.completedTitles||doneFor(date))}else{renderPhotos();doneSnapshot(doneFor(date))}}catch(e){console.error(e);toast('일기를 불러오지 못했어요.')}}
function fileUrl(f){return new Promise((resolve,reject)=>{const r=new FileReader;r.onload=()=>resolve(r.result);r.onerror=reject;r.readAsDataURL(f)})}
async function compress(f){const src=await fileUrl(f),img=await new Promise((resolve,reject)=>{const im=new Image();im.onload=()=>resolve(im);im.onerror=reject;im.src=src}),max=1600,scale=Math.min(1,max/Math.max(img.width,img.height)),c=document.createElement('canvas');c.width=Math.max(1,Math.round(img.width*scale));c.height=Math.max(1,Math.round(img.height*scale));c.getContext('2d').drawImage(img,0,0,c.width,c.height);return c.toDataURL('image/jpeg',.82)}
async function openCurrent(){if(key){await renderCalendar();await openDate(selectedDate)}}
q('#diaryUnlockBtn').onclick=passwordDialog;q('#diaryLockBtn').onclick=lock;q('#openDiaryFromSettingsBtn').onclick=()=>{const tab=q('[data-view="diary"]');if(tab)tab.click();if(!key)passwordDialog()};q('#lockDiaryFromSettingsBtn').onclick=()=>key?lock():toast('일기는 이미 잠겨 있어요.');
q('#diaryPasswordSubmit').onclick=async()=>{const has=!!auth(),p=q('#diaryPasswordInput').value,c=q('#diaryPasswordConfirm').value;q('#diaryPasswordError').textContent='';if(p.length<4){q('#diaryPasswordError').textContent='비밀번호는 4자 이상으로 입력해주세요.';return}if(!has&&p!==c){q('#diaryPasswordError').textContent='비밀번호 확인이 일치하지 않아요.';return}q('#diaryPasswordSubmit').disabled=true;try{if(has){if(!await unlock(p)){q('#diaryPasswordError').textContent='비밀번호가 맞지 않아요.';return}}else await setup(p);q('#diaryPasswordDialog').close();updateGate();await openCurrent();toast(has?'일기를 열었어요.':'일기 비밀번호를 만들었어요.')}finally{q('#diaryPasswordSubmit').disabled=false}};
q('#prevMonthBtn').onclick=async()=>{month=new Date(month.getFullYear(),month.getMonth()-1,1);await renderCalendar()};q('#nextMonthBtn').onclick=async()=>{month=new Date(month.getFullYear(),month.getMonth()+1,1);await renderCalendar()};q('#goTodayBtn').onclick=async()=>{const d=new Date();selectedDate=dateKey(d);month=new Date(d.getFullYear(),d.getMonth(),1);await renderCalendar();await openDate(selectedDate)};
qa('#moodChoices button').forEach(b=>b.onclick=()=>{mood=b.dataset.mood;qa('#moodChoices button').forEach(x=>x.classList.toggle('selected',x===b));resetLock()});
q('#diaryPhotoInput').onchange=async e=>{if(!key)return;const fs=[...e.target.files].slice(0,12-photos.length);if(!fs.length)return;toast('사진을 준비하고 있어요.');for(const f of fs){try{photos.push(await compress(f))}catch(e){console.error(e)}}e.target.value='';renderPhotos();resetLock()};
q('#saveDiaryBtn').onclick=async()=>{if(!key){passwordDialog();return}resetLock();const data={date:selectedDate,mood,text:q('#diaryText').value.trim(),tags:q('#diaryTags').value.split(',').map(x=>x.trim()).filter(Boolean).slice(0,20),photos,completedTitles:doneFor(selectedDate),updatedAt:new Date().toISOString()};if(!data.mood&&!data.text&&!data.tags.length&&!data.photos.length&&!data.completedTitles.length){toast('기록할 내용을 하나라도 남겨주세요.');return}q('#saveDiaryBtn').disabled=true;try{await put(selectedDate,await encrypt(key,data));q('#diarySavedBadge').classList.remove('hidden');await renderCalendar();toast('오늘의 기록을 안전하게 저장했어요.')}catch(e){console.error(e);alert('일기 저장 중 오류가 발생했어요. 브라우저 저장공간을 확인해주세요.')}finally{q('#saveDiaryBtn').disabled=false}};
q('#deleteDiaryBtn').onclick=async()=>{if(!key)return;const row=await get(selectedDate);if(!row){toast('삭제할 일기가 없어요.');return}if(!confirm(`${fmt(selectedDate)} 기록을 삭제할까요?`))return;await del(selectedDate);await renderCalendar();await openDate(selectedDate);toast('일기를 삭제했어요.')};
['diaryText','diaryTags'].forEach(id=>q('#'+id).addEventListener('input',resetLock));
const diaryTab=q('[data-view="diary"]');if(diaryTab)diaryTab.addEventListener('click',()=>setTimeout(()=>{updateGate();openCurrent()},0));
updateGate();
})();
