(()=>{'use strict';
const VERSION='v0.2.0',GOAL_KEY='jjongfocus_goals_v1',TASK_KEY='jjongfocus_v0_1_state';
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const esc=s=>String(s||'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
const uid=()=>crypto.randomUUID?crypto.randomUUID():Date.now().toString(36)+Math.random().toString(36).slice(2);
function loadGoals(){try{return JSON.parse(localStorage.getItem(GOAL_KEY)||'[]')}catch{return[]}}
function saveGoals(x){localStorage.setItem(GOAL_KEY,JSON.stringify(x))}
function taskState(){try{return JSON.parse(localStorage.getItem(TASK_KEY)||'{}')}catch{return{items:[]}}}
function setVersion(){document.title=`쫑포커스 ${VERSION}`;const v=$('.topbar h1 span');if(v)v.textContent=VERSION}
function injectInboxGuide(){const hero=$('#view-inbox .hero-card');if(!hero||$('#inboxGuide'))return;const box=document.createElement('div');box.id='inboxGuide';box.className='inbox-guide';box.innerHTML=`<div><div class="hero-kicker">CLEAR THE INBOX</div><strong id="unclassifiedCount">정리 안 된 생각 0개</strong><p>저장할 때는 생각하지 말고, 나중에 하나씩 의미를 붙여요.</p></div><button id="clarifyOneBtn" class="primary-btn">하나씩 정리</button>`;hero.insertAdjacentElement('afterend',box);$('#clarifyOneBtn').onclick=()=>{const first=$('#inboxList .item-card');if(!first){toast2('정리할 Inbox가 없어요.');return}const b=first.querySelector('[data-act="clarify"]');if(b)b.click()};updateInboxGuide();new MutationObserver(updateInboxGuide).observe($('#inboxList'),{childList:true,subtree:true})}
function updateInboxGuide(){const s=taskState(),n=(s.items||[]).filter(x=>x.status==='inbox'&&(!x.kind||x.kind==='unclassified')).length;const el=$('#unclassifiedCount');if(el)el.textContent=`정리 안 된 생각 ${n}개`}
function toast2(m){const t=$('#toast');if(!t)return;t.textContent=m;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),1800)}
function injectGoals(){if($('[data-view="goals"]'))return;const cal=$('[data-view="calendar"]'),tabs=$('.tabs');if(!tabs)return;const b=document.createElement('button');b.className='tab';b.dataset.view='goals';b.textContent='🎯 목표';(cal||$('[data-view="inbox"]')).insertAdjacentElement('afterend',b);const sec=document.createElement('section');sec.id='view-goals';sec.className='view';sec.innerHTML=`<div class="goals-shell"><div class="goals-head"><div><div class="hero-kicker">DIRECTION</div><h2>🎯 목표</h2><p>막막할 때 큰 목표를 적고, 생각을 펼친 뒤 오늘 할 일로 내려보내요.</p></div><button id="newGoalBtn" class="primary-btn">＋ 새 목표</button></div><div id="goalCreate" class="goal-create hidden"><input id="goalTitle" placeholder="예: Shopee 매출 다시 올리기"><input id="goalWhy" placeholder="왜 중요한가요? (선택)"><button id="saveGoalBtn" class="primary-btn">목표 만들기</button></div><div id="goalList" class="goal-list"></div><div id="goalEmpty" class="record-empty"><div>🎯</div><strong>아직 목표가 없어요.</strong><span>지금 가장 해결하고 싶은 것 하나부터 적어보세요.</span></div></div>`;const now=$('#view-now');now.parentNode.insertBefore(sec,now);
 b.onclick=()=>switchGoals();$('#newGoalBtn').onclick=()=>{$('#goalCreate').classList.toggle('hidden');setTimeout(()=>$('#goalTitle').focus(),20)};$('#saveGoalBtn').onclick=addGoal;$('#goalTitle').addEventListener('keydown',e=>{if(e.key==='Enter'){e.preventDefault();addGoal()}});renderGoals()}
function switchGoals(){$$('.tab').forEach(t=>t.classList.toggle('active',t.dataset.view==='goals'));$$('.view').forEach(v=>v.classList.remove('active'));$('#view-goals').classList.add('active');renderGoals()}
function addGoal(){const title=$('#goalTitle').value.trim(),why=$('#goalWhy').value.trim();if(!title)return;const g=loadGoals();g.unshift({id:uid(),title,why,createdAt:new Date().toISOString(),branches:Array.from({length:8},()=>({text:'',done:false}))});saveGoals(g);$('#goalTitle').value='';$('#goalWhy').value='';$('#goalCreate').classList.add('hidden');renderGoals();toast2('목표를 만들었어요.')}
function renderGoals(){if(!$('#goalList'))return;const gs=loadGoals();$('#goalEmpty').classList.toggle('hidden',gs.length>0);$('#goalList').innerHTML=gs.map(goalCard).join('');$$('[data-goal-branch]').forEach(inp=>inp.onchange=()=>updateBranch(inp));$$('[data-branch-todo]').forEach(b=>b.onclick=()=>branchToTodo(b));$$('[data-goal-del]').forEach(b=>b.onclick=()=>deleteGoal(b.dataset.goalDel))}
function goalCard(g){const filled=(g.branches||[]).filter(x=>x.text).length;return `<article class="goal-card" data-goal="${g.id}"><div class="goal-core"><div><div class="hero-kicker">MAIN GOAL</div><h3>${esc(g.title)}</h3>${g.why?`<p>${esc(g.why)}</p>`:''}</div><div class="goal-progress">${filled}/8</div></div><div class="goal-grid">${(g.branches||[]).map((x,i)=>`<div class="goal-branch"><span>${i+1}</span><input data-goal-branch="${g.id}:${i}" value="${esc(x.text)}" placeholder="생각 ${i+1}"><button data-branch-todo="${g.id}:${i}" ${x.text?'':'disabled'}>Todo</button></div>`).join('')}</div><div class="goal-foot"><span>💡 생각을 8방향으로 펼치고, 실행할 것은 Todo로 보내세요.</span><button class="ghost-btn danger-text" data-goal-del="${g.id}">삭제</button></div></article>`}
function updateBranch(inp){const [id,idx]=inp.dataset.goalBranch.split(':'),gs=loadGoals(),g=gs.find(x=>x.id===id);if(!g)return;g.branches[+idx].text=inp.value.trim();saveGoals(gs);renderGoals()}
function branchToTodo(btn){const [id,idx]=btn.dataset.branchTodo.split(':'),gs=loadGoals(),g=gs.find(x=>x.id===id);if(!g)return;const text=(g.branches[+idx]?.text||'').trim();if(!text)return;try{if(typeof addItem==='function'){const x=addItem({title:text,body:`목표: ${g.title}`});x.kind='task';x.when='today';x.goalId=id;if(typeof saveState==='function')saveState();if(typeof render==='function')render();toast2('오늘 Todo로 보냈어요.');return}}catch(e){console.warn(e)}const s=taskState();s.items=s.items||[];s.items.unshift({id:uid(),type:'note',title:text,body:`목표: ${g.title}`,status:'inbox',createdAt:new Date().toISOString(),kind:'task',when:'today',priority:0,nextAction:'',completedAt:null,goalId:id});localStorage.setItem(TASK_KEY,JSON.stringify(s));toast2('Todo로 저장했어요. 새로고침하면 보여요.')}
function deleteGoal(id){if(!confirm('이 목표를 삭제할까요? Todo로 보낸 항목은 남아 있어요.'))return;saveGoals(loadGoals().filter(x=>x.id!==id));renderGoals()}
function injectStyles(){if($('#focus20Style'))return;const s=document.createElement('style');s.id='focus20Style';s.textContent=`.inbox-guide{display:flex;justify-content:space-between;align-items:center;gap:16px;background:#fff;border:1px solid #e5e7eb;border-radius:18px;padding:15px 17px;margin:14px 0 18px;box-shadow:0 5px 18px rgba(17,24,39,.04)}.inbox-guide strong{font-size:17px}.inbox-guide p{margin:4px 0 0;color:#6b7280;font-size:12px}.goals-shell{display:grid;gap:16px}.goals-head{display:flex;align-items:flex-start;justify-content:space-between;gap:12px}.goals-head h2{margin:3px 0}.goals-head p{margin:0;color:#6b7280}.goal-create{display:grid;grid-template-columns:1fr 1fr auto;gap:8px;background:#fff;border:1px solid #e5e7eb;border-radius:18px;padding:12px}.goal-create input{border:1px solid #dfe3e8;border-radius:12px;padding:11px}.goal-list{display:grid;gap:14px}.goal-card{background:#fff;border:1px solid #e5e7eb;border-radius:22px;padding:17px;box-shadow:0 8px 24px rgba(17,24,39,.04)}.goal-core{display:flex;align-items:flex-start;justify-content:space-between;gap:12px;margin-bottom:13px}.goal-core h3{margin:3px 0 2px;font-size:20px}.goal-core p{margin:0;color:#6b7280;font-size:12px}.goal-progress{min-width:48px;height:48px;border-radius:50%;background:#111827;color:#fff;display:grid;place-items:center;font-weight:900}.goal-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:8px}.goal-branch{display:grid;grid-template-columns:28px minmax(0,1fr) auto;gap:6px;align-items:center;background:#f7f8fa;border-radius:13px;padding:7px}.goal-branch span{width:24px;height:24px;border-radius:50%;background:#fff;display:grid;place-items:center;font-size:11px;font-weight:900}.goal-branch input{min-width:0;border:0;background:transparent;outline:none;font-weight:750}.goal-branch button{border:0;background:#fff;border-radius:9px;padding:6px 8px;font-size:10px;font-weight:850}.goal-branch button:disabled{opacity:.35}.goal-foot{display:flex;justify-content:space-between;align-items:center;gap:10px;margin-top:12px;color:#8a9099;font-size:11px}@media(max-width:720px){.inbox-guide,.goals-head,.goal-foot{align-items:stretch;flex-direction:column}.goal-create{grid-template-columns:1fr}.goal-grid{grid-template-columns:1fr}}`;document.head.appendChild(s)}
function reorderTabs(){const tabs=$('.tabs');if(!tabs)return;const order=['inbox','calendar','goals','now','today','diary','done','settings'];order.forEach(k=>{const t=$(`[data-view="${k}"]`);if(t)tabs.appendChild(t)})}
function ready(){setVersion();injectStyles();injectInboxGuide();injectGoals();reorderTabs()}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',ready);else ready();
})();