(()=>{'use strict';
const DB='jjongkeep_simple_v2',STORE='items',KEY='jjongkeep_lists_v1';let selected='',pickerItem=null,pickerCard=null;
const $=s=>document.querySelector(s);function names(items=[]){let saved=[];try{saved=JSON.parse(localStorage.getItem(KEY)||'[]')}catch{}const used=items.map(i=>(i.list||'').trim()).filter(Boolean);return [...new Set([...saved,...used])].sort((a,b)=>a.localeCompare(b,'ko'))}function saveName(n){n=(n||'').trim();if(!n)return;const a=names();if(!a.includes(n)){a.push(n);localStorage.setItem(KEY,JSON.stringify(a))}}
function dbItems(){return new Promise((res,rej)=>{const r=indexedDB.open(DB,1);r.onsuccess=()=>{const q=r.result.transaction(STORE).objectStore(STORE).getAll();q.onsuccess=()=>res(q.result||[]);q.onerror=()=>rej(q.error)};r.onerror=()=>rej(r.error)})}function put(i){return new Promise((res,rej)=>{const r=indexedDB.open(DB,1);r.onsuccess=()=>{const q=r.result.transaction(STORE,'readwrite').objectStore(STORE).put(i);q.onsuccess=()=>res();q.onerror=()=>rej(q.error)};r.onerror=()=>rej(r.error)})}
async function refresh(){const items=await dbItems(),bar=$('#listFilters');if(!bar)return;const ns=names(items);bar.innerHTML='';const all=document.createElement('button');all.className='list-filter'+(!selected?' active':'');all.textContent='📁 전체';all.onclick=()=>{selected='';refresh();apply()};bar.appendChild(all);ns.forEach(n=>{const b=document.createElement('button');b.className='list-filter'+(selected===n?' active':'');b.textContent='📁 '+n;b.onclick=()=>{selected=n;refresh();apply()};bar.appendChild(b)});const add=document.createElement('button');add.className='list-filter add';add.textContent='＋ 목록';add.onclick=()=>newList();bar.appendChild(add)}
function apply(){document.querySelectorAll('#list .note').forEach(card=>{const n=card.dataset.list||'';card.style.display=!selected||n===selected?'':'none'})}
function ensurePicker(){if($('#listPicker'))return;const d=document.createElement('div');d.id='listPicker';d.className='list-picker hidden';d.innerHTML='<div class="list-picker-sheet"><div class="list-picker-head"><strong>목록 선택</strong><button type="button" class="list-picker-close">✕</button></div><div id="listPickerOptions" class="list-picker-options"></div><button type="button" id="listPickerNew" class="list-picker-new">＋ 새 목록 만들기</button><button type="button" id="listPickerClear" class="list-picker-clear">목록 해제</button></div>';document.body.appendChild(d);d.querySelector('.list-picker-close').onclick=closePicker;d.onclick=e=>{if(e.target===d)closePicker()};$('#listPickerNew').onclick=()=>newList(true);$('#listPickerClear').onclick=()=>chooseList('')}
async function openPicker(item,card){pickerItem=item;pickerCard=card;ensurePicker();const items=await dbItems(),box=$('#listPickerOptions');box.innerHTML='';const ns=names(items);if(!ns.length){const p=document.createElement('div');p.className='list-picker-empty';p.textContent='아직 만든 목록이 없어요.';box.appendChild(p)}ns.forEach(n=>{const b=document.createElement('button');b.type='button';b.className='list-picker-option'+(item.list===n?' active':'');b.textContent='📁 '+n;b.onclick=()=>chooseList(n);box.appendChild(b)});$('#listPickerClear').classList.toggle('hidden',!item.list);$('#listPicker').classList.remove('hidden')}
function closePicker(){const d=$('#listPicker');if(d)d.classList.add('hidden');pickerItem=pickerCard=null}async function chooseList(n){if(!pickerItem)return;const item=pickerItem,card=pickerCard,scrollY=window.scrollY;item.list=n;if(n)saveName(n);item.updatedAt=Date.now();await put(item);if(card){card.dataset.list=n;const b=card.querySelector('.list-chip');if(b){b.textContent=n?'📁 '+n:'📁 목록';b.classList.toggle('selected',!!n)}}closePicker();await refresh();apply();requestAnimationFrame(()=>window.scrollTo(0,scrollY))}
function newList(fromPicker=false){const n=prompt('새 목록 이름을 입력하세요.');if(!n?.trim())return;saveName(n.trim());if(fromPicker&&pickerItem)chooseList(n.trim());else{selected=n.trim();refresh();apply()}}
function collapse(card){const text=card.querySelector('.note-text');if(!text||text.dataset.collapseBound)return;text.dataset.collapseBound='1';requestAnimationFrame(()=>{if(text.scrollHeight<=text.clientHeight+4)return;const b=document.createElement('button');b.type='button';b.className='note-more';b.textContent='더보기';b.onclick=()=>{const open=text.classList.toggle('expanded');b.textContent=open?'접기':'더보기'};text.insertAdjacentElement('afterend',b)})}
function decorate(){document.querySelectorAll('#list .note').forEach(card=>{collapse(card);if(card.dataset.listBound)return;card.dataset.listBound='1';const source=card.querySelector('.note-source');if(!source)return;const text=source.textContent||'',created=text.includes('공유로 들어옴')?'share':'direct';dbItems().then(items=>{const candidates=items.filter(i=>(created==='share'?i.source==='share':i.source!=='share'));const stamp=i=>new Date(i.createdAt).toLocaleString('ko-KR',{month:'numeric',day:'numeric',hour:'2-digit',minute:'2-digit'});let item=candidates.find(i=>text.includes(stamp(i)));if(!item)return;card.dataset.list=item.list||'';const actions=card.querySelector('.note-actions:last-child');if(!actions)return;const b=document.createElement('button');b.className='pill list-chip'+(item.list?' selected':'');b.textContent=item.list?'📁 '+item.list:'📁 목록';b.onclick=()=>openPicker(item,card);actions.insertBefore(b,actions.lastElementChild)}).catch(()=>{})});apply()}
const obs=new MutationObserver(()=>decorate());function init(){const list=$('#list');if(!list)return;ensurePicker();obs.observe(list,{childList:true,subtree:false});refresh();decorate()}document.readyState==='loading'?document.addEventListener('DOMContentLoaded',init):init();})();