(()=>{'use strict';
const VERSION='v0.2.1',LOG_KEY='jjongfocus_recovery_log_v1',TASK_KEY='jjongfocus_v0_1_state';
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const esc=s=>String(s||'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
const nowIso=()=>new Date().toISOString();
let mood='',dump='',groups=null,candidate=null,shrinkLevel=0,savedBrainId=null;
function loadLog(){try{return JSON.parse(localStorage.getItem(LOG_KEY)||'[]')}catch{return[]}}
function saveLog(x){localStorage.setItem(LOG_KEY,JSON.stringify(x.slice(0,80)))}
function log(type,text,meta={}){const a=loadLog();a.unshift({id:Date.now()+Math.random(),at:nowIso(),type,text,meta});saveLog(a)}
function taskState(){try{return JSON.parse(localStorage.getItem(TASK_KEY)||'{}')}catch{return{items:[]}}}
function toast(m){const t=$('#toast');if(!t)return;t.textContent=m;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),1800)}
function addCss(){if($('#recoveryCss'))return;const l=document.createElement('link');l.id='recoveryCss';l.rel='stylesheet';l.href='./recovery.css?v=021';document.head.appendChild(l)}
function setVersion(){document.title=`쫑포커스 ${VERSION}`;const v=$('.topbar h1 span');if(v)v.textContent=VERSION}
function createUi(){if($('#recoveryDialog'))return;const top=$('.topbar');if(top&&!$('#recoveryBtn')){const b=document.createElement('button');b.id='recoveryBtn';b.className='recovery-launch';b.textContent='🌿 다시 돌아오기';top.appendChild(b);b.onclick=openStart}
 const d=document.createElement('dialog');d.id='recoveryDialog';d.className='recovery-dialog';d.innerHTML='<div id="recoveryRoot"></div>';document.body.appendChild(d);d.addEventListener('click',e=>{if(e.target===d)d.close()});
 injectLostButton();renderStart();}
function injectLostButton(){const now=$('#view-now .focus-shell');if(!now||$('#lostBtn'))return;const box=document.createElement('div');box.className='recovery-back';box.innerHTML='<strong>놓쳤구나.</strong><br>지나간 시간은 그대로 두고, 지금 다시 돌아오면 돼.<div class="recovery-actions"><button id="lostBtn" class="recovery-soft">🌿 다시 돌아오기</button></div>';now.appendChild(box);$('#lostBtn').onclick=openStart}
function head(title,sub){return `<div class="recovery-head"><div><div class="recovery-kicker">RETURN TO NOW</div><h2>${esc(title)}</h2><p class="recovery-sub">${esc(sub)}</p></div><button class="recovery-close" data-close>✕</button></div>`}
function bindClose(){const b=$('[data-close]');if(b)b.onclick=()=>$('#recoveryDialog').close()}
function openStart(){mood='';dump='';groups=null;candidate=null;shrinkLevel=0;savedBrainId=null;renderStart();const d=$('#recoveryDialog');if(typeof d.showModal==='function')d.showModal();else d.setAttribute('open','');setTimeout(()=>$('#recoveryDump')?.focus(),80)}
function renderStart(){const r=$('#recoveryRoot');if(!r)return;r.innerHTML=`<div class="recovery-shell">${head('지금 어떤 상태야?','해결하려고 애쓰지 말고, 먼저 지금 상태를 확인해요.')}<div class="recovery-state-grid"><button class="recovery-state" data-mood="괜찮아">🙂 괜찮아</button><button class="recovery-state" data-mood="머리가 복잡해">😵 머리가 복잡해</button><button class="recovery-state" data-mood="마음이 힘들어">😔 마음이 힘들어</button><button class="recovery-state" data-mood="아무것도 하기 싫어">🛌 아무것도 하기 싫어</button></div><div class="recovery-box"><label class="recovery-label" for="recoveryDump">지금 머릿속에 있는 걸 아무렇게나 적어봐</label><textarea id="recoveryDump" class="recovery-textarea" placeholder="할 일, 걱정, 감정, 아이디어… 순서 없이 적어도 괜찮아요."></textarea><div class="recovery-actions"><button id="recoveryOrganize" class="recovery-primary">정리해줘</button><button id="recoverySaveOnly" class="recovery-ghost">그냥 저장</button><button id="recoveryTimelineBtn" class="recovery-soft">오늘 기록</button></div></div></div>`;bindClose();$$('[data-mood]').forEach(b=>b.onclick=()=>{mood=b.dataset.mood;$$('[data-mood]').forEach(x=>x.classList.toggle('selected',x===b))});$('#recoveryOrganize').onclick=organize;$('#recoverySaveOnly').onclick=saveOnly;$('#recoveryTimelineBtn').onclick=renderTimeline}
function splitThoughts(text){return text.split(/\n+|(?<=[.!?])\s+|\s*[,;]\s*/).map(x=>x.trim()).filter(x=>x.length>1)}
function classify(text){const g={feel:[],fixed:[],task:[],worry:[],idea:[],other:[]};for(const s of splitThoughts(text)){if(/아이디어|기능|만들면|생각났|해보면/.test(s)){g.idea.push(s);continue}if(/해야|하자|할 일|수정|확인|등록|리스팅|플딜|flash|작업|보내|연락|예약|구매|정리|준비/.test(s)){g.task.push(s);continue}if(/걱정|어떡|어쩌지|될까|떨어질까|망할|미래|불안/.test(s)){g.worry.push(s);continue}if(/과거|이미 일어|지나간|바꿀 수 없|되돌릴 수 없/.test(s)){g.fixed.push(s);continue}if(/괴롭|힘들|우울|짜증|답답|무기력|피곤|슬프|화나|기분|싫어/.test(s)){g.feel.push(s);continue}g.other.push(s)}return g}
function saveDumpToInbox(text){if(!text.trim())return null;try{if(typeof addItem==='function'){const x=addItem({type:'brain',title:'지금 머릿속',body:text});savedBrainId=x.id;return x}}catch(e){console.warn(e)}return null}
function addTaskFromText(text){if(!text)return null;try{if(typeof addItem==='function'){const x=addItem({title:text,body:'쫑포커스 다시 돌아오기에서 만든 행동'});x.kind='task';x.when='today';x.nextAction=text;if(typeof saveState==='function')saveState();if(typeof render==='function')render();return x}}catch(e){console.warn(e)}return null}
function existingCandidate(){const s=taskState(),items=(s.items||[]).filter(x=>x.status==='inbox'&&(x.kind==='task'||x.kind==='unclassified'));items.sort((a,b)=>{const ax=a.when==='today'?1:0,bx=b.when==='today'?1:0;return bx-ax||String(b.createdAt||'').localeCompare(String(a.createdAt||''))});return items[0]||null}
function organize(){dump=$('#recoveryDump').value.trim();if(!dump){toast('한 줄만 적어도 괜찮아요.');return}groups=classify(dump);saveDumpToInbox(dump);const taskText=groups.task[0]||'';candidate=taskText?addTaskFromText(taskText):existingCandidate();log('organize',dump.slice(0,120),{mood,task:candidate?.title||''});renderResult()}
function saveOnly(){dump=$('#recoveryDump').value.trim();if(!dump){toast('저장할 내용을 적어주세요.');return}saveDumpToInbox(dump);log('save',dump.slice(0,120),{mood});toast('그냥 저장했어요. 정리는 나중에 해도 돼요.');$('#recoveryDialog').close()}
function listHtml(a){return a?.length?`<ul>${a.map(x=>`<li>${esc(x)}</li>`).join('')}</ul>`:'<div class="recovery-sub">지금은 없음</div>'}
function renderResult(){const r=$('#recoveryRoot');if(!r)return;r.innerHTML=`<div class="recovery-shell">${head('머릿속에서 조금 꺼냈어','정답을 내리는 게 아니라, 서로 다른 것들을 잠깐 나눠놓는 단계예요.')}<div class="recovery-result-grid"><div class="recovery-result ${groups.feel.length?'':'empty'}"><h4>💭 지금 마음</h4>${listHtml(groups.feel)}</div><div class="recovery-result ${groups.fixed.length?'':'empty'}"><h4>🪨 지금 바꾸기 어려운 것</h4>${listHtml(groups.fixed)}</div><div class="recovery-result ${groups.task.length?'':'empty'}"><h4>✅ 실제로 할 일</h4>${listHtml(groups.task)}</div><div class="recovery-result ${groups.worry.length?'':'empty'}"><h4>🌫 머릿속 걱정</h4>${listHtml(groups.worry)}</div>${groups.idea.length?`<div class="recovery-result"><h4>💡 아이디어</h4>${listHtml(groups.idea)}</div>`:''}${groups.other.length?`<div class="recovery-result"><h4>📝 기타 생각</h4>${listHtml(groups.other)}</div>`:''}</div><div class="recovery-note">전부 해결할 필요 없어. 지금은 다시 삶으로 돌아갈 길 하나만 고르면 돼.</div><div class="recovery-actions"><button id="toOne" class="recovery-primary">지금 하나</button><button id="backStart" class="recovery-ghost">다시 적기</button></div></div>`;bindClose();$('#toOne').onclick=renderOne;$('#backStart').onclick=renderStart}
function currentAction(){if(!candidate)return '5분 쉬고 다시 돌아오기';const base=(candidate.nextAction||candidate.title||'지금 할 일 하나').trim();if(shrinkLevel===0)return base;if(shrinkLevel===1)return `관련 화면 하나만 열기 · ${base}`;if(shrinkLevel===2)return 'PC나 휴대폰 앞에 앉아 2분만 보기';return '5분 쉬고 다시 돌아오기'}
function renderOne(){const action=currentAction(),r=$('#recoveryRoot');if(!r)return;r.innerHTML=`<div class="recovery-shell">${head('지금 하나만','완벽하게 끝내는 게 아니라, 다시 접촉하는 게 목표예요.')}<div class="recovery-one"><div class="recovery-kicker">JUST ONE</div><h3>${esc(action)}</h3><p>${candidate?'이것 하나만 시작하면 돼. 시작하고 괜찮아지면 더 하고, 아니면 여기까지.':'지금은 할 일을 고르는 것보다 상태를 조금 낮추는 게 먼저일 수 있어.'}</p><div class="recovery-actions"><button id="startOne" class="recovery-primary">▶ 시작하기</button><button id="tooHard" class="recovery-soft">이것도 힘들어</button></div></div><div class="recovery-back"><strong>놓쳤구나.</strong><br>오늘 오전을 다 놓쳤어도, 며칠 멈췄어도 지금 다시 돌아오면 돼.</div><div class="recovery-actions"><button id="showLogs" class="recovery-ghost">오늘 기록 보기</button></div></div>`;bindClose();$('#startOne').onclick=startOne;$('#tooHard').onclick=()=>{shrinkLevel=Math.min(3,shrinkLevel+1);renderOne()};$('#showLogs').onclick=renderTimeline}
function startOne(){const action=currentAction();log('start',action,{mood,itemId:candidate?.id||null,level:shrinkLevel});if(candidate&&shrinkLevel<3){try{const x=typeof state!=='undefined'&&state.items?state.items.find(z=>z.id===candidate.id):null;if(x){x.nextAction=action;if(typeof saveState==='function')saveState();if(typeof handleAction==='function'){handleAction(candidate.id,'now');$('#recoveryDialog').close();return}}}catch(e){console.warn(e)}}if(shrinkLevel>=3){toast('5분 쉬고, 돌아오고 싶을 때 다시 열면 돼요.')}else toast('아주 작게 시작해요.');$('#recoveryDialog').close()}
function renderTimeline(){const logs=loadLog().filter(x=>new Date(x.at).toDateString()===new Date().toDateString()).slice(0,12),r=$('#recoveryRoot');if(!r)return;r.innerHTML=`<div class="recovery-shell">${head('오늘 돌아온 기록','점수는 없어요. 멈췄다가 돌아온 흔적만 남겨요.')}<div class="recovery-box"><div class="recovery-timeline">${logs.length?logs.map(x=>{const t=new Date(x.at).toLocaleTimeString('ko-KR',{hour:'2-digit',minute:'2-digit'});const label=x.type==='start'?'다시 시작':x.type==='organize'?'머릿속 정리':'그냥 저장';return `<div class="recovery-log"><time>${esc(t)}</time><div><strong>${label}</strong><br>${esc(x.text)}</div></div>`}).join(''):'<div class="recovery-empty">아직 기록이 없어요. 오늘 첫 번째로 돌아와도 돼요.</div>'}</div></div><div class="recovery-actions"><button id="timelineBack" class="recovery-primary">다시 돌아오기</button></div></div>`;bindClose();$('#timelineBack').onclick=renderStart}
function ready(){addCss();setVersion();createUi();}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',ready);else ready();
})();
