const CACHE='jjongkeep-v033',DB='jjongkeep_simple_v2',STORE='items',DIAG='jjongkeep-diag';
self.addEventListener('install',()=>self.skipWaiting());
self.addEventListener('activate',e=>e.waitUntil(self.clients.claim()));
async function diag(data){try{const c=await caches.open(DIAG);await c.put('/last',new Response(JSON.stringify(data)))}catch(e){}}
function uid(){return crypto.randomUUID?crypto.randomUUID():Date.now().toString(36)+Math.random().toString(36).slice(2)}
function normalizeRecord(input){const t=Date.now(),created=Number(input.createdAt)||t;return {...input,text:typeof input.text==='string'?input.text:'',photos:Array.isArray(input.photos)?input.photos:[],contentBlocks:Array.isArray(input.contentBlocks)?input.contentBlocks:[],lists:Array.isArray(input.lists)?input.lists:[],list:typeof input.list==='string'?input.list:'',type:input.type||'reference',priorityScore:Number.isFinite(Number(input.priorityScore))?Number(input.priorityScore):50,prioritySet:!!input.prioritySet,today:!!input.today,todayOrder:input.today?(Number(input.todayOrder)||created):null,completed:!!input.completed,completedAt:input.completed?(Number(input.completedAt)||null):null,archived:!!input.archived,scheduleDate:input.scheduleDate||'',scheduleEndDate:input.scheduleEndDate||'',scheduleTime:input.scheduleTime||'',source:input.source||'share',createdAt:created,updatedAt:Number(input.updatedAt)||created,inboxOrder:Number(input.inboxOrder)||created,listNewAt:Number(input.listNewAt)||0,schemaVersion:1}}
function openDb(){return new Promise((res,rej)=>{const r=indexedDB.open(DB,1);r.onupgradeneeded=()=>{if(!r.result.objectStoreNames.contains(STORE))r.result.createObjectStore(STORE,{keyPath:'id'})};r.onsuccess=()=>res(r.result);r.onerror=()=>rej(r.error)})}
async function saveItem(item){const db=await openDb();await new Promise((res,rej)=>{const t=db.transaction(STORE,'readwrite');t.oncomplete=res;t.onerror=()=>rej(t.error);t.onabort=()=>rej(t.error);t.objectStore(STORE).put(normalizeRecord(item))});db.close()}
function findBytes(hay,needle,from=0){outer:for(let i=from;i<=hay.length-needle.length;i++){for(let j=0;j<needle.length;j++)if(hay[i+j]!==needle[j])continue outer;return i}return -1}
function parseMultipart(buf,ct){const m=/boundary=(?:"([^"]+)"|([^;]+))/i.exec(ct);if(!m)throw Error('boundary 없음');const boundary=m[1]||m[2];const enc=new TextEncoder(),dec=new TextDecoder();const bytes=new Uint8Array(buf);const marker=enc.encode('--'+boundary);const sep=enc.encode('\r\n\r\n');const parts=[];let pos=findBytes(bytes,marker,0);while(pos>=0){let start=pos+marker.length;if(bytes[start]===45&&bytes[start+1]===45)break;if(bytes[start]===13&&bytes[start+1]===10)start+=2;const headerEnd=findBytes(bytes,sep,start);if(headerEnd<0)break;const headers=dec.decode(bytes.slice(start,headerEnd));let bodyStart=headerEnd+sep.length;let next=findBytes(bytes,marker,bodyStart);if(next<0)break;let bodyEnd=next;if(bodyEnd>=2&&bytes[bodyEnd-2]===13&&bytes[bodyEnd-1]===10)bodyEnd-=2;const name=/name="([^"]+)"/i.exec(headers);if(name){const file=/filename="([^"]*)"/i.exec(headers);const type=/Content-Type:\s*([^\r\n]+)/i.exec(headers);parts.push({name:name[1],file:file?file[1]:'',type:type?type[1].trim():'',bytes:bytes.slice(bodyStart,bodyEnd)})}pos=next}return parts}
async function receive(req,d){d.stage='요청 도착';d.contentType=req.headers.get('content-type')||'';await diag(d);const buf=await req.arrayBuffer();d.stage='원본 body 읽기 성공';d.rawBytes=buf.byteLength;await diag(d);const parts=parseMultipart(buf,d.contentType);d.parts=parts.length;let title='',text='',url='',photos=[];const dec=new TextDecoder('utf-8');for(const p of parts){if(p.file){if(p.type.startsWith('image/'))photos.push(new Blob([p.bytes],{type:p.type}))}else{const v=dec.decode(p.bytes).replace(/\r\n$/,'').trim();if(p.name==='title')title=v;else if(p.name==='text')text=v;else if(p.name==='url')url=v}}d.stage='내용 추출 성공';d.title=title.length;d.text=text.length;d.url=url.length;d.photos=photos.length;await diag(d);const words=[title,text,url].filter((v,i,a)=>v&&a.indexOf(v)===i);if(!words.length&&!photos.length)throw Error('내용 없음');d.stage='IndexedDB 저장 시작';await diag(d);const t=Date.now();await saveItem({id:uid(),text:words.join('\n\n'),photos,contentBlocks:[],lists:[],list:'',type:'reference',priorityScore:50,prioritySet:false,today:false,todayOrder:null,completed:false,completedAt:null,archived:false,scheduleDate:'',scheduleEndDate:'',scheduleTime:'',source:'share',createdAt:t,updatedAt:t,inboxOrder:t,listNewAt:0,schemaVersion:1});d.stage='IndexedDB 저장 완료';d.ok=true;await diag(d)}
self.addEventListener('fetch',e=>{const u=new URL(e.request.url);if(e.request.method==='POST'&&u.pathname==='/share-target'){e.respondWith((async()=>{const d={ok:false};try{await receive(e.request,d);return Response.redirect(new URL('/?shared=1',self.registration.scope).href,303)}catch(err){d.error=(err&&err.name?err.name+': ':'')+(err&&err.message?err.message:String(err));await diag(d);return Response.redirect(new URL('/?shareError=1',self.registration.scope).href,303)}})());return}if(e.request.method==='GET')e.respondWith(fetch(e.request).catch(()=>caches.match(e.request).then(r=>r||caches.match('/index.html'))))});