const CACHE='jjongkeep-v031',DB='jjongkeep_simple_v2',STORE='items',DIAG='jjongkeep-diag';
self.addEventListener('install',e=>{self.skipWaiting()});
self.addEventListener('activate',e=>e.waitUntil(self.clients.claim()));
async function diag(data){try{const c=await caches.open(DIAG);await c.put('/last',new Response(JSON.stringify(data)))}catch(e){}}
function uid(){return crypto.randomUUID?crypto.randomUUID():Date.now().toString(36)+Math.random().toString(36).slice(2)}
function openDb(){return new Promise((res,rej)=>{const r=indexedDB.open(DB,1);r.onupgradeneeded=()=>{if(!r.result.objectStoreNames.contains(STORE))r.result.createObjectStore(STORE,{keyPath:'id'})};r.onsuccess=()=>res(r.result);r.onerror=()=>rej(r.error)})}
async function saveItem(item){const db=await openDb();await new Promise((res,rej)=>{const t=db.transaction(STORE,'readwrite');t.oncomplete=res;t.onerror=()=>rej(t.error);t.onabort=()=>rej(t.error);t.objectStore(STORE).put(item)});db.close()}
function parse(buf,ct){const m=/boundary=(?:"([^"]+)"|([^;]+))/i.exec(ct);if(!m)throw Error('boundary 없음');const boundary=m[1]||m[2],s=new TextDecoder('latin1').decode(new Uint8Array(buf)),out=[];for(const part of s.split('--'+boundary)){const n=part.indexOf('\r\n\r\n');if(n<0)continue;const h=part.slice(0,n);let b=part.slice(n+4);if(b.endsWith('\r\n'))b=b.slice(0,-2);const name=/name="([^"]+)"/i.exec(h);if(!name)continue;const file=/filename="([^"]*)"/i.exec(h),type=/Content-Type:\s*([^\r\n]+)/i.exec(h);out.push({name:name[1],file:file?file[1]:'',type:type?type[1].trim():'',bytes:Uint8Array.from(b,c=>c.charCodeAt(0))})}return out}
async function receive(req,d){d.stage='요청 도착';d.contentType=req.headers.get('content-type')||'';await diag(d);const buf=await req.arrayBuffer();d.stage='원본 body 읽기 성공';d.rawBytes=buf.byteLength;await diag(d);const parts=parse(buf,d.contentType);d.parts=parts.length;let title='',text='',url='',photos=[];for(const p of parts){if(p.file){if(p.type.startsWith('image/'))photos.push(new Blob([p.bytes],{type:p.type}))}else{const v=new TextDecoder().decode(p.bytes).trim();if(p.name==='title')title=v;if(p.name==='text')text=v;if(p.name==='url')url=v}}d.stage='내용 추출 성공';d.title=title.length;d.text=text.length;d.url=url.length;d.photos=photos.length;await diag(d);const words=[title,text,url].filter((v,i,a)=>v&&a.indexOf(v)===i);if(!words.length&&!photos.length)throw Error('내용 없음');d.stage='IndexedDB 저장 시작';await diag(d);await saveItem({id:uid(),text:words.join('\n\n'),photos,type:'reference',today:false,archived:false,source:'share',createdAt:Date.now(),updatedAt:Date.now()});d.stage='IndexedDB 저장 완료';d.ok=true;await diag(d)}
self.addEventListener('fetch',e=>{const u=new URL(e.request.url);if(e.request.method==='POST'&&u.pathname==='/share-target'){e.respondWith((async()=>{const d={ok:false};try{await receive(e.request,d);return Response.redirect(new URL('/?shared=1&diag=1',self.registration.scope).href,303)}catch(err){d.error=(err&&err.name?err.name+': ':'')+(err&&err.message?err.message:String(err));await diag(d);return Response.redirect(new URL('/?shareError=1&diag=1',self.registration.scope).href,303)}})());return}if(e.request.method==='GET')e.respondWith(fetch(e.request).catch(()=>caches.match(e.request).then(r=>r||caches.match('/index.html'))))});