const CACHE='jjongkeep-v030',DB='jjongkeep_simple_v2',STORE='items';
self.addEventListener('install',e=>{e.waitUntil(caches.open(CACHE).then(c=>c.addAll(['/','/index.html','/jjongkeep.css?v=030','/jjongkeep.js?v=030','/manifest.webmanifest?v=030']).catch(()=>{}));self.skipWaiting()});
self.addEventListener('activate',e=>e.waitUntil(Promise.all([self.clients.claim(),caches.keys().then(ks=>Promise.all(ks.filter(k=>k!==CACHE).map(k=>caches.delete(k))))])));
function uid(){return crypto.randomUUID?crypto.randomUUID():Date.now().toString(36)+Math.random().toString(36).slice(2)}
function openDb(){return new Promise((res,rej)=>{const r=indexedDB.open(DB,1);r.onupgradeneeded=()=>{if(!r.result.objectStoreNames.contains(STORE))r.result.createObjectStore(STORE,{keyPath:'id'})};r.onsuccess=()=>res(r.result);r.onerror=()=>rej(r.error)})}
async function saveItem(item){const db=await openDb();await new Promise((res,rej)=>{const t=db.transaction(STORE,'readwrite');t.oncomplete=res;t.onerror=()=>rej(t.error);t.onabort=()=>rej(t.error);t.objectStore(STORE).put(item)});db.close()}
function rawParts(buf,ct){const m=/boundary=(?:"([^"]+)"|([^;]+))/i.exec(ct||'');if(!m)throw Error('boundary 없음');const boundary=m[1]||m[2],bytes=new Uint8Array(buf),latin=new TextDecoder('latin1').decode(bytes),chunks=latin.split('--'+boundary),out=[];for(const chunk of chunks){const cut=chunk.indexOf('\r\n\r\n');if(cut<0)continue;const head=chunk.slice(0,cut);let body=chunk.slice(cut+4);if(body.endsWith('\r\n'))body=body.slice(0,-2);const nm=/name="([^"]+)"/i.exec(head);if(!nm)continue;const fm=/filename="([^"]*)"/i.exec(head),tm=/Content-Type:\s*([^\r\n]+)/i.exec(head);const bodyBytes=Uint8Array.from(body,c=>c.charCodeAt(0));out.push({field:nm[1],filename:fm?fm[1]:'',type:tm?tm[1].trim():'',bytes:bodyBytes})}return out}
function decodeText(bytes){try{return new TextDecoder('utf-8').decode(bytes)}catch{return ''}}
async function receive(req){const ct=req.headers.get('content-type')||'',clone=req.clone();let title='',text='',url='',photos=[];try{const f=await req.formData();title=String(f.get('title')||'').trim();text=String(f.get('text')||'').trim();url=String(f.get('url')||'').trim();photos=f.getAll('files').filter(x=>x&&typeof x==='object'&&x.size>0)}catch(e){const buf=await clone.arrayBuffer(),parts=rawParts(buf,ct);for(const p of parts){if(p.filename){if((p.type||'').startsWith('image/'))photos.push(new Blob([p.bytes],{type:p.type||'image/jpeg'}))}else{const v=decodeText(p.bytes).trim();if(p.field==='title')title=v;else if(p.field==='text')text=v;else if(p.field==='url')url=v}}}
 const pieces=[];for(const v of [title,text,url])if(v&&!pieces.includes(v))pieces.push(v);if(!pieces.length&&!photos.length)throw Error('공유된 내용 없음');await saveItem({id:uid(),text:pieces.join('\n\n'),photos,type:'reference',today:false,archived:false,source:'share',createdAt:Date.now(),updatedAt:Date.now()})}
self.addEventListener('fetch',e=>{const u=new URL(e.request.url);if(e.request.method==='POST'&&u.pathname==='/share-target'){e.respondWith((async()=>{try{await receive(e.request);return Response.redirect(new URL('/?shared=1',self.registration.scope).href,303)}catch(err){return Response.redirect(new URL('/?shareError=1',self.registration.scope).href,303)}})());return}if(e.request.method==='GET')e.respondWith(fetch(e.request).then(r=>{const cp=r.clone();caches.open(CACHE).then(c=>c.put(e.request,cp)).catch(()=>{});return r}).catch(()=>caches.match(e.request).then(x=>x||caches.match('/index.html'))))});