(()=>{'use strict';
const q=s=>document.querySelector(s),qa=s=>[...document.querySelectorAll(s)];
const AUTH='jjongfocus_diary_auth_v1',DB='jjongfocus_diary_db_v1',TODO='jjongfocus_v0_1_state';
let key=null,day=dk(new Date()),month=new Date(new Date().getFullYear(),new Date().getMonth(),1),photos=[],mood='',types=new Set(),lockTimer=null;
const meta={thought:['💭','생각'],emotion:['😊','감정'],idea:['💡','아이디어'],task:['✅','할 일'],reference:['📚','참고'],diary:['📔','일기']};
const esc=s=>String(s||'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
const toast=m=>{const t=q('#toast');if(!t)return;t.textContent=m;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),1700)};
function dk(d){return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`}
function fmt(x){const [y,m,d]=x.split('-').map(Number);return new Intl.DateTimeFormat('ko-KR',{year:'numeric',month:'long',day:'numeric',weekday:'long'}).format(new Date(y,m-1,d))}
function tf(x){return new Intl.DateTimeFormat('ko-KR',{hour:'2-digit',minute:'2-digit'}).format(new Date(x))}
function uid(){return crypto.randomUUID?crypto.randomUUID():Date.now().toString(36)+Math.random().toString(36).slice(2)}
function auth(){try{return JSON.parse(localStorage.getItem(AUTH)||'null')}catch{return null}}
function b64(a){let s='';a.forEach(v=>s+=String.fromCharCode(v));return btoa(s)}
function unb64(s){const x=atob(s),a=new Uint8Array(x.length);for(let i=0;i<x.length;i++)a[i]=x.charCodeAt(i);return a}
async function derive(p,salt){const raw=await crypto.subtle.importKey('raw',new TextEncoder().encode(p),'PBKDF2',false,['deriveKey']);return crypto.subtle.deriveKey({name:'PBKDF2',salt,iterations:150000,hash:'SHA-256'},raw,{name:'AES-GCM',length:256},false,['encrypt','decrypt'])}
async function encryptWith(k,obj){const iv=crypto.getRandomValues(new Uint8Array(12)),plain=new TextEncoder().encode(JSON.stringify(obj)),cipher=await crypto.subtle.encrypt({name:'AES-GCM',iv},k,plain);return{iv:b64(iv),data:b64(new Uint8Array(cipher))}}
async function decryptWith(k,p){const plain=await crypto.subtle.decrypt({name:'AES-GCM',iv:unb64(p.iv)},k,unb64(p.data));return JSON.parse(new TextDecoder().decode(plain))}
function db(){return new Promise((ok,no)=>{const r=indexedDB.open(DB,2);r.onupgradeneeded=()=>{const d=r.result;if(!d.objectStoreNames.contains('entries'))d.createObjectStore('entries',{keyPath:'date'});if(!d.objectStoreNames.contains('records')){const s=d.createObjectStore('records',{keyPath:'id'});s.createIndex('date','date')}};r.onsuccess=()=>ok(r.result);r.onerror=()=>no(r.error)})}
async function addRow(r){const d=await db();return new Promise((ok,no)=>{const t=d.transaction('records','readwrite');t.objectStore('records').put(r);t.oncomplete=()=>{d.close();ok()};t.onerror=()=>{d.close();no(t.error)}})}
async function deleteRow(id){const d=await db();return new Promise(ok=>{const t=d.transaction('records','readwrite');t.objectStore('records').delete(id);t.oncomplete=()=>{d.close();ok()}})}
async function rowsFor(date){const d=await db();return new Promise((ok,no)=>{const t=d.transaction('records'),r=t.objectStore('records').index('date').getAll(date);r.onsuccess=()=>{d.close();ok(r.result||[])};r.onerror=()=>{d.close();no(r.error)}})}
async function allRows(){const d=await db();return new Promise(ok=>{const t=d.transaction('records'),r=t.objectStore('records').getAll();r.onsuccess=()=>{d.close();ok(r.result||[])}})}
async function migrateOld(){if(!key)return;const d=await db();if(!d.objectStoreNames.contains('entries')){d.close();return}const old=await new Promise(ok=>{const t=d.transaction('entries'),r=t.objectStore('entries').getAll();r.onsuccess=()=>ok(r.result||[]);r.onerror=()=>ok([])});d.close();for(const row of old){try{const o=await decryptWith(key,row.payload);const existing=await rowsFor(row.date);if(existing.some(x=>x.migratedFromOld))continue;const rec={id:uid(),date:row.date,createdAt:o.updatedAt||`${row.date}T21:00:00`,text:o.text||'',mood:o.mood||'',types:o.tags?.length?['diary']:['diary'],photos:o.photos||[],oldTags:o.tags||[]};await addRow({id:rec.id,date:rec.date,payload:await encryptWith(key,rec),migratedFromOld:true})}catch{}}
}
function setupUI(){document.title='쫑포커스 v0.1.7.1';const v=q('.topbar h1 span');if(v)v.textContent='v0.1.7.1';const tab=q('[data-view="diary"]');if(tab)tab.textContent='📖 기록';q('#view-diary').innerHTML=`<div id="diaryLocked" class="diary-lock-card"><div class="lock-emoji">🔒</div><div class="hero-kicker">PRIVATE RECORDS</div><h2>나만 보는 순간 기록</h2><p id="diaryLockText"></p><button id="diaryUnlockBtn" class="primary-btn">기록 열기</button></div><div id="diaryContent" class="hidden"><div class="diary-toolbar"><div><div class="hero-kicker">MY TIMELINE</div><h2>📖 기록</h2><p>분류보다 기록이 먼저. 순간을 남기고 필요할 때 할 일·아이디어로 바꿔요.</p></div><button id="diaryLockBtn" class="ghost-btn">🔒 잠그기</button></div><div class="diary-grid"><aside class="calendar-card"><div class="calendar-head"><button id="prevMonthBtn" class="icon-btn">‹</button><strong id="calendarTitle"></strong><button id="nextMonthBtn" class="icon-btn">›</button></div><div class="calendar-week"><span>일</span><span>월</span><span>화</span><span>수</span><span>목</span><span>금</span><span>토</span></div><div id="calendarGrid" class="calendar-grid"></div><button id="goTodayBtn" class="ghost-btn calendar-today-btn">오늘로 이동</button></aside><div class="record-main"><div class="record-date-head"><div class="hero-kicker">SELECTED DAY</div><h2 id="diaryDateTitle"></h2><p id="recordDaySummary"></p></div><div class="record-composer"><textarea id="recordText" rows="4" placeholder="지금 떠오른 생각, 감정, 메모를 그냥 적으세요."></textarea><div class="record-quick-row"><div id="moodChoices" class="mood-row compact-moods">${['😄','🙂','😐','😔','😡','😴'].map(x=>`<button type="button" data-mood="${x}">${x}</button>`).join('')}</div><label class="photo-add-btn file-btn">📸 사진<input id="recordPhotoInput" type="file" accept="image/*" multiple></label></div><div id="recordPhotoPreview" class="diary-photos"></div><div class="field-label">필요하면 표시만 해두세요 · 여러 개 선택 가능</div><div id="recordTypeChoices" class="record-type-row">${Object.entries(meta).map(([k,v])=>`<button type="button" data-type="${k}">${v[0]} ${v[1]}</button>`).join('')}</div><div class="record-composer-actions"><span class="hint">아무것도 고르지 않아도 저장할 수 있어요.</span><button id="addRecordBtn" class="primary-btn">＋ 지금 기록</button></div></div><div class="timeline-head"><strong>오늘의 타임라인</strong><span id="recordCount"></span></div><div id="recordTimeline" class="record-timeline"></div><div id="recordEmpty" class="record-empty"><div>🕰️</div><strong>아직 기록이 없어요.</strong><span>한 줄 메모부터 남겨보세요.</span></div></div></div></div>`;
const s=document.createElement('style');s.textContent=`.record-main{min-width:0}.record-date-head h2{margin:4px 0 2px;font-size:26px}.record-date-head p{margin:0 0 12px;color:#6b7280;font-size:13px}.record-composer{background:#fff;border:1px solid #e5e7eb;border-radius:22px;padding:18px;box-shadow:0 8px 24px rgba(17,24,39,.05);margin-bottom:18px}.record-composer textarea{width:100%;border:0;background:#f7f8fa;border-radius:16px;padding:15px;resize:vertical;outline:none;line-height:1.6}.record-quick-row{display:flex;align-items:center;justify-content:space-between;gap:10px;margin:10px 0}.compact-moods{margin:0}.compact-moods button{min-width:38px;padding:8px}.record-type-row{display:flex;flex-wrap:wrap;gap:7px}.record-type-row button{border:1px solid #e5e7eb;background:#fff;border-radius:999px;padding:8px 11px;font-weight:750;cursor:pointer}.record-type-row button.selected{background:#111827;color:#fff}.record-composer-actions{display:flex;justify-content:space-between;align-items:center;gap:12px;margin-top:14px}.timeline-head{display:flex;justify-content:space-between;margin:18px 2px 10px}.record-timeline{display:grid;gap:12px}.record-card{position:relative;background:#fff;border:1px solid #e5e7eb;border-radius:18px;padding:16px 16px 14px 70px}.record-time{position:absolute;left:8px;top:18px;width:55px;font-size:11px;font-weight:850;color:#6b7280}.record-time span{font-size:17px}.record-tags{display:flex;flex-wrap:wrap;gap:5px;margin-bottom:8px}.record-tag{font-size:11px;font-weight:800;padding:4px 7px;border-radius:999px;background:#f1f3f5}.record-text{white-space:pre-wrap;line-height:1.6}.record-card-photos{display:grid;grid-template-columns:repeat(auto-fill,minmax(110px,1fr));gap:7px;margin-top:10px}.record-card-photos img{width:100%;aspect-ratio:1;object-fit:cover;border-radius:12px}.record-actions{display:flex;flex-wrap:wrap;gap:6px;margin-top:12px}.record-actions button{border:0;background:#f1f3f5;border-radius:10px;padding:7px 9px;font-size:11px;font-weight:800}.record-actions .del{margin-left:auto;color:#a33}.record-empty{text-align:center;border:1px dashed #d8dbe0;border-radius:18px;padding:48px 20px;color:#8a9099;display:flex;flex-direction:column;gap:5px}.calendar-day{position:relative}.calendar-day small{position:absolute;right:3px;bottom:2px;min-width:15px;height:15px;line-height:15px;border-radius:99px;background:#111827;color:#fff;font-size:8px}@media(max-width:720px){.record-composer-actions,.record-quick-row{align-items:stretch;flex-direction:column}.record-card{padding-left:58px}.record-card-photos{grid-template-columns:repeat(2,1fr)}}`;document.head.appendChild(s)}
function gate(){const a=auth(),open=!!key;q('#diaryLocked').classList.toggle('hidden',open);q('#diaryContent').classList.toggle('hidden',!open);q('#diaryLockText').textContent=a?'비밀번호를 입력하면 나만의 기록을 볼 수 있어요.':'비밀번호를 만들면 모든 기록을 암호화해서 저장해요.';q('#diaryUnlockBtn').textContent=a?'🔓 비밀번호로 열기':'🔐 비밀번호 만들기'}
function resetLock(){clearTimeout(lockTimer);if(key)lockTimer=setTimeout(()=>{key=null;gate();toast('기록을 자동으로 잠갔어요.')},600000)}
function openPasswordDialog(){const has=!!auth();q('#diaryPasswordTitle').textContent=has?'기록 잠금 해제':'기록 비밀번호 만들기';q('#diaryPasswordHelp').textContent=has?'기존에 만든 비밀번호를 그대로 입력하세요.':'4자 이상으로 만들어주세요.';q('#diaryPasswordInput').value='';q('#diaryPasswordConfirm').value='';q('#diaryPasswordConfirm').classList.toggle('hidden',has);q('#diaryPasswordError').textContent='';q('#diaryPasswordSubmit').textContent=has?'열기':'만들기';q('#diaryPasswordDialog').showModal()}
async function unlock(p){const a=auth();if(!a||!a.salt||!a.verifier)return false;try{const k=await derive(p,unb64(a.salt));const v=await decryptWith(k,a.verifier);if(v?.ok!=='jjongfocus-diary')return false;key=k;resetLock();return true}catch(e){console.warn('unlock failed',e);return false}}
async function makePassword(p){const salt=crypto.getRandomValues(new Uint8Array(16));const k=await derive(p,salt);const verifier=await encryptWith(k,{ok:'jjongfocus-diary'});localStorage.setItem(AUTH,JSON.stringify({salt:b64(salt),verifier,version:1}));key=k;resetLock()}
function fileData(f){return new Promise((ok,no)=>{const r=new FileReader;r.onload=()=>ok(r.result);r.onerror=no;r.readAsDataURL(f)})}
async function compress(f){const src=await fileData(f),im=await new Promise((ok,no)=>{const x=new Image();x.onload=()=>ok(x);x.onerror=no;x.src=src}),sc=Math.min(1,1400/Math.max(im.width,im.height)),c=document.createElement('canvas');c.width=Math.round(im.width*sc);c.height=Math.round(im.height*sc);c.getContext('2d').drawImage(im,0,0,c.width,c.height);return c.toDataURL('image/jpeg',.8)}
function renderPhotoPreview(){q('#recordPhotoPreview').innerHTML=photos.map((x,i)=>`<div class="diary-photo"><img src="${x}"><button type="button" data-rm="${i}">×</button></div>`).join('');qa('[data-rm]').forEach(b=>b.onclick=()=>{photos.splice(+b.dataset.rm,1);renderPhotoPreview()})}
function clearComposer(){q('#recordText').value='';photos=[];mood='';types.clear();qa('#moodChoices button,#recordTypeChoices button').forEach(b=>b.classList.remove('selected'));renderPhotoPreview()}
async function decoded(date){const out=[];for(const row of await rowsFor(date)){try{out.push(await decryptWith(key,row.payload))}catch{}}return out.sort((a,b)=>new Date(a.createdAt)-new Date(b.createdAt))}
function card(r){const tags=(r.types||[]).map(t=>meta[t]?`<span class="record-tag">${meta[t][0]} ${meta[t][1]}</span>`:'').join('');const pics=(r.photos||[]).length?`<div class="record-card-photos">${r.photos.map(x=>`<img src="${x}">`).join('')}</div>`:'';return `<article class="record-card" data-id="${r.id}"><div class="record-time">${tf(r.createdAt)}${r.mood?` <span>${r.mood}</span>`:''}</div>${tags?`<div class="record-tags">${tags}</div>`:''}${r.text?`<div class="record-text">${esc(r.text)}</div>`:''}${pics}<div class="record-actions"><button data-to="task">✅ 할 일로</button><button data-to="idea">💡 아이디어로</button><button data-to="reference">📚 참고로</button><button class="del" data-del>삭제</button></div></article>`}
function sendToInbox(r,kind){const body=(r.text||'').trim()||`${fmt(r.date)} 기록`,title=body.split(/\n/)[0].slice(0,44);try{if(typeof addItem==='function'){const x=addItem({type:'note',title,body,image:(r.photos||[])[0]||null});x.kind=kind;x.when=kind==='task'?'today':'';saveState();render();toast(kind==='task'?'할 일로 보냈어요.':kind==='idea'?'아이디어로 보냈어요.':'참고로 보냈어요.');return}}catch(e){console.error(e)}toast('전환에 실패했어요.')}
async function renderTimeline(){const a=await decoded(day);q('#recordTimeline').innerHTML=a.map(card).join('');q('#recordCount').textContent=`${a.length}개 기록`;q('#recordDaySummary').textContent=a.length?`이 날 ${a.length}개의 순간을 남겼어요.`:'아직 기록이 없어요.';q('#recordEmpty').classList.toggle('hidden',!!a.length);qa('[data-del]').forEach(b=>b.onclick=async()=>{if(!confirm('이 기록을 삭제할까요?'))return;await deleteRow(b.closest('[data-id]').dataset.id);await renderTimeline();await renderCalendar()});qa('[data-to]').forEach(b=>b.onclick=()=>{const r=a.find(x=>x.id===b.closest('[data-id]').dataset.id);sendToInbox(r,b.dataset.to)})}
async function renderCalendar(){const counts={};for(const r of await allRows())counts[r.date]=(counts[r.date]||0)+1;const y=month.getFullYear(),m=month.getMonth();q('#calendarTitle').textContent=`${y}년 ${m+1}월`;const start=new Date(y,m,1-new Date(y,m,1).getDay()),cells=[];for(let i=0;i<42;i++){const d=new Date(start);d.setDate(start.getDate()+i);const k=dk(d),n=counts[k]||0;cells.push(`<button class="calendar-day${d.getMonth()!==m?' outside':''}${k===dk(new Date())?' today':''}${k===day?' selected':''}" data-date="${k}">${d.getDate()}${n?`<small>${n}</small>`:''}</button>`)}q('#calendarGrid').innerHTML=cells.join('');qa('[data-date]').forEach(b=>b.onclick=async()=>{day=b.dataset.date;const z=day.split('-');month=new Date(+z[0],+z[1]-1,1);q('#diaryDateTitle').textContent=fmt(day);clearComposer();await renderCalendar();await renderTimeline()})}
async function openAll(){if(!key)return;resetLock();q('#diaryDateTitle').textContent=fmt(day);await migrateOld();await renderCalendar();await renderTimeline()}
setupUI();gate();
q('#diaryUnlockBtn').onclick=openPasswordDialog;q('#diaryLockBtn').onclick=()=>{key=null;gate();toast('기록을 잠갔어요.')};
q('#openDiaryFromSettingsBtn').onclick=()=>{q('[data-view="diary"]').click();if(!key)openPasswordDialog()};q('#lockDiaryFromSettingsBtn').onclick=()=>{key=null;gate()};
q('#diaryPasswordSubmit').onclick=async()=>{const has=!!auth(),p=q('#diaryPasswordInput').value,c=q('#diaryPasswordConfirm').value;q('#diaryPasswordError').textContent='';if(p.length<4){q('#diaryPasswordError').textContent='4자 이상 입력해주세요.';return}if(!has&&p!==c){q('#diaryPasswordError').textContent='비밀번호가 일치하지 않아요.';return}q('#diaryPasswordSubmit').disabled=true;try{if(has){if(!await unlock(p)){q('#diaryPasswordError').textContent='비밀번호를 확인해주세요. 기존 v0.1.6 비밀번호도 그대로 사용할 수 있어요.';return}}else await makePassword(p);q('#diaryPasswordDialog').close();gate();await openAll();toast('기록을 열었어요.')}finally{q('#diaryPasswordSubmit').disabled=false}};
q('#prevMonthBtn').onclick=async()=>{month=new Date(month.getFullYear(),month.getMonth()-1,1);await renderCalendar()};q('#nextMonthBtn').onclick=async()=>{month=new Date(month.getFullYear(),month.getMonth()+1,1);await renderCalendar()};q('#goTodayBtn').onclick=async()=>{const d=new Date;day=dk(d);month=new Date(d.getFullYear(),d.getMonth(),1);q('#diaryDateTitle').textContent=fmt(day);clearComposer();await renderCalendar();await renderTimeline()};
qa('#moodChoices button').forEach(b=>b.onclick=()=>{mood=mood===b.dataset.mood?'':b.dataset.mood;qa('#moodChoices button').forEach(x=>x.classList.toggle('selected',x.dataset.mood===mood));if(mood)types.add('emotion');qa('#recordTypeChoices button').forEach(x=>x.classList.toggle('selected',types.has(x.dataset.type)))});
qa('#recordTypeChoices button').forEach(b=>b.onclick=()=>{types.has(b.dataset.type)?types.delete(b.dataset.type):types.add(b.dataset.type);b.classList.toggle('selected',types.has(b.dataset.type))});
q('#recordPhotoInput').onchange=async e=>{for(const f of [...e.target.files].slice(0,8-photos.length))photos.push(await compress(f));e.target.value='';renderPhotoPreview()};
q('#addRecordBtn').onclick=async()=>{const text=q('#recordText').value.trim();if(!text&&!photos.length&&!mood){toast('한 줄 메모, 감정, 사진 중 하나는 남겨주세요.');return}const n=new Date,rec={id:uid(),date:day,createdAt:day===dk(n)?n.toISOString():`${day}T12:00:00`,text,mood,types:[...types],photos:[...photos]};await addRow({id:rec.id,date:day,payload:await encryptWith(key,rec)});clearComposer();await renderTimeline();await renderCalendar();toast('순간을 기록했어요.')};
q('[data-view="diary"]').addEventListener('click',()=>setTimeout(()=>{gate();openAll()},0));
})();